### PR TITLE
Wear Move latest remaining Display setting from Phone to Watch (prediction lines)

### PR DESCRIPTION
**Pull request by Philoul**
Now all display settings concerning watchfaces are on Watch side

### CODE REVIEW

**Comment by Philoul** [comment]
@MilosKozak Do you know if we have an easy way to organize Watch settings ?
=> I tried to use `<PreferenceCategory` within `preference.xml` file to organize preferences within Watch but it crashed immediatly...

The idea was to have an intermediate layer with for example: (currently we have close to 30 items now within watch...)
- Display settings
- Graph settings
- User interface settings
- Complication settings

**Comment by MilosKozak** [comment]
because wear app works only with main app i'd agree with moving settings to phone

**Comment by jbr7rr** [comment]
+1 for moving all/most wear settings to phone app instead of in wear. It's fiddly to change settings on watch. Especially when there are 30+ items in the menu ;)

**Comment by Philoul** [comment]
@jbr7rr see #2753 to start discussion on improvements...

**Pull request merged**
