### PR TITLE
Increase height of Compact Tab and Profile/TT row

### PR DESCRIPTION
**Pull request by Philoul**
Some users have difficulties in Compact mode to select the 3 dots or hamburger menus due to height too small.
=> I propose to use same Height for Compact tabs than Standard tabs
=> I increased a little bit height of Profile / Target buttons for the same reason

### CODE REVIEW

**Comment by osodebailar** [comment]
Do you have to pictures with before and after ?

**Comment by Philoul** [comment]
See screenshots below (in french)
Screenshot_20201224-115432_AndroidAPS

**Comment by Philoul** [comment]
If the height increase is too much for compact tabs, I can just increase the default compact height a bit (currently 30dp, something between 40dp and 48dp might be a good compromise)

**Comment by osodebailar** [comment]
I think it's a good solution . 
It's nearly the same as I did in my bottom toolbar in my GUI fork. And as I know all users are very satisfied with the size .

I would prefer your solution .

**Comment by MilosKozak** [comment]
how does it look like with short names used?

**Comment by Philoul** [comment]
In my first proposal, Heigth of Compact menu was the same than Standard menu (but I think it's too important), so I made a second commit to increase a little bit Compact height (see in screenshot below on the left current heights, in the middle first version and on the left  with latest commit.
Screenshot_20201225-164639_AndroidAPS

**Comment by AdrianLxM** [comment]
Up until Android 9 I'd have said: For the compact one I'd go with the first.

Now with swipe gestures to go back on newer Android versions people might actually want to press the burger button. As the gesture to open the drawer and "back" conflicts.

**Pull request merged**
