### PR TITLE
Fix Graph rescale very slow

### PR DESCRIPTION
**Pull request by Philoul**
I modified OverviewData to always prepare MaxRange for 24h + Prediction duration and store MaxRanges in a table according to selected scale (6h, 12h, 18h or 24h) and prediction duration/selection
=> When we change scale I just return correct Array and associated MaxRange so everything is shown very quickly in overview

The Prepare duration is a bit longer (always 24h + prediction duration, and not only selected range), but rescale is much quicker
Only remaining problem during my tests, if I try to rescale graph during the countdown of received new BG value (there are to many thing to do for the App and I can still get App not responding popup)

### CODE REVIEW

**Comment by Philoul** [comment]
the objective of this PR is to Fix #801 and #899

**Comment by MilosKozak** [comment]
I don't like these copy/pasted classes. it makes hard maintaing the code

**Comment by Philoul** [comment]
I'm agree, I don't like too, I just did it quickly based on my previous work (and having something that works for historybrowser)
I propose to revert last commit, but it will be necessary to find a solution for historyBrowser that doesn't work with modification made...

**Comment by rustymonkey** [comment]
Tested this PR on 2.8.2.10dev 2021-11-14-12:49, and it resolves the issue. i.e.
- the UI now responds consistently to Tap-hold actions
- tap-hold actions no longer trigger the 'AndroidAPS isn't responding' dialog

**Comment by vanelsberg** [comment]
@Philoul Thanks for taking this improvement. Much appreciated.

**Comment by vanelsberg** [comment]
See also https://github.com/nightscout/AndroidAPS/pull/911

**Comment by Philoul** [comment]
I started to work to find a solution to also improve history browser that share same code in a different way, but still remains bugs so work is still in progress...

**Comment by Philoul** [comment]
Now it works with Historybrowser
- No optimisation for HistoryBrowser (too complicated to do without Room database)
- For Overview, I always prepare 24hours of graph data (with Arrays of all Max values calculated for 6, 12, 18 and 24, with and without prediction)
- On rescale, I just build Series on the fly according to range selected and I return associated max Values

@vanelsberg @rustymonkey Can you tell me if it works fine on your phones ? (In overview, with and without prediction curves, and in History Browser)

**Comment by vanelsberg** [comment]
@Philoul Just installed 1196/911 on my test phone (realized I did not  need an active DASH Pod on it)
Test phone: Nokia 5.4. Decent phone, not high-end.

**Rescaling 6/12/18/24hrs:
**Yes!** This is exactly what I needed: not only is it fast. I can now select preference range without rotating to al others! Love it!

**History viewer:**
Imho this really is a huge improvement. User interface changed from "...never mind" to "interesting!" ;-)
I see still some lagging when switching dates, but also delays are "acceptable" compared to what it was. I think for the user it is clear the system is working on a lot of data, so the need to wait feels ok?

- *Bug?*:  I can still long-press the Graph selection button. It presents the range 6/12/18/24 selection dropdown as on overview. However it does not work. Would suggest to disable log-press when in the history viewer?

Just tested for about 20 minutes selecting different ranges on overview an history browser.
How not seen any problem. Also no 


At a 6 hour window

**Comment by vanelsberg** [comment]
For PR#1196/911: Suggest to freeze code as is, test for any bugs and then make this into a PR?
(When this gets merged with dev I think you will have a lot of testers getting out any problems that are in)

Would love to have this on 3.0 release or else as a fix shortly after.

**Comment by Philoul** [comment]
> Bug?: I can still long-press the Graph selection button. It presents the range 6/12/18/24

I'll test again, it should work in history browser too 🤔

**Comment by Philoul** [comment]
> History viewer:
Imho this really is a huge improvement. User interface changed from "...never mind" to "interesting!" ;-)

#911 doesn't improve history browser, (@MilosKozak fixed it in v3.0, we have some ideas to improve it but not in v3...)., the only improvement will come from #1196 and #1142 (if  they work...)

**Comment by vanelsberg** [comment]
@Philoul Ok? But why do I see both overview and history browser rendering so much better? 
Then it must be #1196 - can't imagine it's the Phone (Samsung Not 9 vs Nokia 5.4)? 

Will retest today with the Note 9 to see....)

**Comment by Philoul** [comment]
Phone is probably the best explain...
I have huge differences between my loop phone (Samsung A40, very good 2 years ago but a nightmare now), and my test phone (power U20 bought 2 months ago for my dev config).
I never got Aaps not responding on my dev phone, and updates after each bg received or each graph rescale is quicker on my new dev phone...

**Comment by vanelsberg** [comment]
@Philoul Phone (and possible database?) has impact, only I do not get it:
For history viewer Testphone (Nokia 5.4) performs a lot better for history viewer (even though it is buggy)

Decided to test on main phone (Note 9, which has much higher specs then the Nokia);
- Overview ranging also works great and performs better then current dev!
- History browser: seems to have a lot of problems and after changing range and dates started to lock up AAPS completely. So much that I had to kill the app (close/wait pop-up). On restart it quickly became unresponsive again. Solved by updating to current stable version.

**My Conclusion on PR#1196+911 on for now:**
- Overview ranging with pop-up menue does great. Love it!
- History browser is still buggy and locks up AAPS when using (result may depend on setup).
Will do some retesting on the separate PR's

**Comment by Philoul** [comment]
@vanelsberg Thanks
I think #1196 is ok but still remains improvements in history browser in this PR to be able to merge...

**Comment by vanelsberg** [comment]
@Philoul Agree.
Yes really like current functionality for #1196 works. Even with current performance.
Even asking myself if we need the current way for range switching: replace current long-press on overview to present the range pop-up?

**Comment by rustymonkey** [comment]
Tested 2022-01-07 build with this PR and all is working well: 
- Changing the Overview graph scale works well.
- Notwithstanding your comments, history browser does seem a bit faster with this PR (though as with the regular build the graph flashes more as additional data is displayed (e.g. Activity + graph 1 with IOB & COB).

**Comment by Philoul** [comment]
Much quicker on latest version

**Pull request closed without merging**
