### PR TITLE
Support automatic exchange of communication key for HTTP via connecti…

### PR DESCRIPTION
**Pull request by buessow**
…q native comm (usually unreliable but could enough for that).

### CODE REVIEW

**Comment by MilosKozak** [comment]
https://notifications.googleapis.com/email/redirect?t=AFG8qyUuHhOGC5EDSvNjSJYv9ESL8vme-O717QvRqtdsaTWK7oYvNyYSdLk7XuqYapEMLran8XA-BBcYrvEE6IGsEN7j99P16qem-J_BMUDVSbRrdkDkpy4u-mWm6gspVLsJaF2iUFY6Tec0dayU-GH9XqdqkMZZUa2q7cO0l1jcYfYDhzX9lyRGl6XuzJFniURjbV6cTHhWEfeP4eFDu_BLtz-gTr1o1i-w_Ue2jx9gB1UJNQOyNZ4LCuxr&r=eJxFy9EKgzAMQNEvskHrnApj3xLTVDu0KU0c-Pfby9jjhXM3s6IzAElW2dnFVHlBZbeKrN8mOaBUeTEZYA5VUsCiDfk-jkAVddsvS6SApfzAnHIUl9O6mZKc5v4jJNWTFTy2_RgwdhO2i196xm7wdOMYcLi3PD0tHfzYUa1RfnNuAl76AaAgPqo&s=ALHZ2r7-NwXRTJxpW3x0KlkDVViX

**Comment by buessow** [comment]
Thanks, Milos. Unfortunately, I cannot open the link.

**Comment by MilosKozak** [comment]
Fatal Exception: android.os.BadParcelableException: Overflow in the size of parcelable
       at com.garmin.android.connectiq.IQDevice.readFromParcel(IQDevice.java:48)
       at com.garmin.android.connectiq.IQDevice$1.createFromParcel(IQDevice.java:14)
       at com.garmin.android.connectiq.IQDevice$1.createFromParcel(IQDevice.java:10)
       at android.os.Parcel.readTypedObject(Parcel.java:4025)
       at android.os.Parcel.createTypedArrayList(Parcel.java:3671)
       at com.garmin.android.apps.connectmobile.connectiq.IConnectIQService$Stub$Proxy.getConnectedDevices(IConnectIQService.java:233)
       at app.aaps.plugins.sync.garmin.GarminDeviceClient$ciqServiceConnection$1.onServiceConnected(GarminDeviceClient.kt:92)
       at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:2198)
       at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2231)
       at android.os.Handler.handleCallback(Handler.java:958)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:205)
       at android.os.Looper.loop(Looper.java:294)
       at android.app.ActivityThread.main(ActivityThread.java:8177)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)

**Comment by swissalpine** [comment]
By the way, it would have been nice if you had not only gone your own private way when implementing the web service, but also adhered to the quasi-standard set by Nightscout for the responses.
In any case, JamOrHam and I rebuilt the Nightscout api when installing the web service in xDrip so that it is as open as possible for others. Diabox, Juglucco, Spike and others are currently imitating this interface. This makes it relatively easy for app developers on various watches (Fitbit, Garmin, etc.) to program an interface for several "connections".
Now the web service is only there for your Garmin apps. A private solution, so to speak - but maybe something can be changed.

**Comment by MilosKozak** [comment]
@buessow what with this PR? it has conflicts

**Comment by buessow** [comment]
@MilosKozak I resolved the conflicts. Please take another look.

**Pull request merged**
