### PR TITLE
watchface  - configuration activities for individually watchface settings

### PR DESCRIPTION
**Pull request by rICTx-T1D**
Some settings are located in global configuration dialog, but they only work on individually watchface. With watchface "digitalStyle" a new way to configure the individual  was going. 

The goal of this PullRequest is relocate follow individual setting:
- All **except** for Cockpit and Steampunk: Dark (default On)
- AAPS: Matching divider (default Off)
- AAPSv2: Matching divider (default Off)
- AAPSv2: Show Date (default Off)
- AAPS(Large): Matching divider (default Off)
- Steampunk: Delta Granularity (default Medium)
- Circle WF: Big Numbers (default Off)
- Circle WF: Ring History (default Off)
- Circle WF: Light Ring History (default On)
- Circle WF: Animations (default On)
- DigitalStyle: Show Week number (default Off)
- DigitalStyle: Show Date (default On)

### CODE REVIEW

**Comment by rICTx-T1D** [comment]
This settings was moved to individual Watchface configuration:
`   

    

    

    

    

    

    

    

    `

**Comment by AdrianLxM** [comment]
I wonder if we shouldn't keep the general settings still in as older watches don't have watchface specific settings?

**Comment by rICTx-T1D** [comment]
> I wonder if we shouldn't keep the general settings still in as older watches don't have watchface specific settings?

Hi @AdrianLxM ,
all wearos-version 2 0 and higher watches have this feature integrated.  The recommended way to make settings is this, when you study google wearos developer guides. 
Additional I think, the layout of watchface is in some cases not run-ready before wearos v2.0. Also we have settings there only for one or some watchfaces implemented and user are confused when the setting is not working.

**Comment by AdrianLxM** [comment]
Unfortunately the Sony Smartwatch 3 never got the update to 2.0

**Comment by rICTx-T1D** [comment]
@AdrianLxM 
I think some watchfaces are wrong rendered, because the relativerendering with adaptive pixel size was improved in wearos 2.x. How old is this watch? AAPS doesn't support Android 4 and lower and some users has very old devices in your storage too.

**Comment by AdrianLxM** [comment]
The watch is a few year's old but still I would bet the most used with AndroidAPS.
Especially as many bought it to scan the libre.
The watchfaces were developed with that watch in the test pool.

**Comment by rICTx-T1D** [comment]
@AdrianLxM 
I must correct my statement. WearOS1.x has the configuration activity for watchfaces too. Only the configuration activity for compilation is new in WearOS 2.x, because the compilations are a new 2.x Feature.

Please test the changes with your old watch, because I don't have the Chance to do this. Generaly the core team must make things, how long old functions will be support. In AAPS on Phone, all phones under Android 7 are not supported.

**Comment by AdrianLxM** [comment]
@rICTx-T1D A quick FB survey showed that more than 100 people still actively use that watch. (Probably many more)
And you are absolutely right, the Sony Smartwatch 3 will have the setting for the watchface individually then and they work :) 

Could you please remove the commented out, now obsolete sections and we can merge this PR? :)

Thanks a lot!

**Comment by rICTx-T1D** [comment]
@AdrianLxM  
Thanks for testing with your watch. The uncomment code was removed yet. So I think its ready to merge.

**Pull request merged**
