### PR TITLE
WIP Refactor

### PR DESCRIPTION
**Pull request by MilosKozak**

### CODE REVIEW

**Comment by Philoul** [comment]
- do you planned to also include triple up and down management within AAPS ? (included in enum but never used in UI)
- it would be fine if in wear we receive TrendArrow enum object instead of "arrow string"...

**Comment by MilosKozak** [comment]
> * do you planned to also include triple up and down management within AAPS ? (included in enum but never used in UI)
> * it would be fine if in wear we receive TrendArrow enum object instead of "arrow string"...

I don't know if it's even used anywhere

**Comment by MilosKozak** [comment]
> * do you planned to also include triple up and down management within AAPS ? (included in enum but never used in UI)
> * it would be fine if in wear we receive TrendArrow enum object instead of "arrow string"...

TrendArrow yes, but after I finish this

**Comment by MilosKozak** [comment]
The goal is to split database and code completely

**Pull request closed without merging**
