### PR TITLE
Wizard Icons -> Allow both: Enable and Disable

### PR DESCRIPTION
**Pull request by swissalpine**
So far it is only possible (thanks to @Philooul) that a click on the icon disables the function. This PR also allows to enable bg, trend, carbs and iob if disabled while clicking on the icon.

### CODE REVIEW

**Comment by Philoul** [comment]
Not needed, my PR already allow Enable And Disable...

**Comment by MilosKozak** [comment]
I agree with @Philoul . His code is more elegant

**Comment by swissalpine** [comment]
Shure, I know the behaviour of the iob Check Box.
But I couldn't reactivate BG etc. after disabling it first. Would you see a screen video top beliebte me?

**Comment by Philoul** [comment]
Yes, icons are small so I'm not surprised it could be difficult to click on them.
Can you send a screenshot of your small screen (to check if we can increase a bit size, margin or padding of these icons on low res screen...)

**Comment by swissalpine** [comment]
Too late. I have long since adjusted the for me. But if you like, I restore an old version ...
Screenshot_20220114-062916
The size of the icons is 0.7, so you can roughly estimate that there is hardly any space.
"Cancel" is then abbreviated to "Canc".

**Comment by Philoul** [comment]
We have a Low res skin in AAPS...
It's better if we use low res skin to adapt these kind of user interface that doesn't work on small phones..

**Comment by swissalpine** [comment]
What are you trying to tell me: that I shouldn't change it like that for myself - or that I should do a PR with this adjustment?
There is much more changed here: e.g. fixed font sizes, but also the alpha values for the icons, because otherwise the icons are hardly to be seen ...

**Comment by Philoul** [comment]
I think, each time you detect something that need improvements for low res screen, it's better if you open an issue with your proposal (screenshot before/after)
Some of your modifications can be included for all users that have small phones with "low res skin" selection in preferences...

**Pull request closed without merging**
