### PR TITLE
WIP: Add support for doc help links

### PR DESCRIPTION
**Pull request by Andries-Smit**
As a (new) user I need to go back and forward 100 or more times between the app and the documentation site. The process is frustrating and time consuming. I could learn the app quicker if I can access the documentation direction from the app.

With this PR we can integrate help links in the app on most screens to point to the right part of the documentation website. 

Features:
- Help button top right corner of dialogs
- Plugins can have help URL show in via config menu
- Active selected tab have in the menu a help item enabled if there is a help URL available 

image
image
image

TODO
- [ ] Add more links
- [ ] Add tests
- [x] Code refactor (Open Helper, UI Help Dialog fragment)

Discuss
- [ ] URL structure for documentation. Can we make the link language independent? {baseUrl}/{lang}/{version}/{path}/{achor}
- [ ] Versioning doc to prevent dead link when docs structure changes in future releases
- [ ] Multi lingual links
- [ ] Which pages, dialogs, plugins and pages should have a help link
- [ ] Preference option to hide the help link (to not change the UI for existing users)?
- [ ] Preference option to select doc version: "Current" / "Latest"
- [ ] Should main menu Help test be dynamic? "{Plugin} Help" similar as the preference?
- [ ] When a module does not have a help you be disabled or hidden?
- [ ] Should we add Add URL tester in the build to prevent broken links? (This might be slow if tested against live doc site)

### CODE REVIEW

**Comment by StephenBrown2** [comment]
As a user, I LOVE this idea. However, with a changing product, the maintenance of such links will be a consideration.

> URL structure for documentation. Can we make the link language independent? {baseUrl}/{lang}/{version}/{path}/{achor}

As for language-based links, they could be gotten from the current language that's set in the app (or on the device), and default to English if not found.

The lost of docs languages and app translations would need to be kept in sync, but maybe they already are?
From the docs https://github.com/openaps/AndroidAPSdocs/blob/master/docs/index.rst :
```
   English </EN/index>
   Česky (Czech) </CROWDIN/cs/index>
   Deutsch (German) </CROWDIN/de/index>
   Ελληνικά (Greek) </CROWDIN/el/index>
   Español (Spanish) </CROWDIN/es/index>
   한국어 (Korean) </CROWDIN/ko/index>
   Lietuvių kalba (Lithuanian) </CROWDIN/lt/index>
   Nederlands (Dutch) </CROWDIN/nl/index>
   Polski (Polish) </CROWDIN/pl/index>
   Русский (Russian) </CROWDIN/ru/index>
   Slovensky (Slovak) </CROWDIN/sk/index>
```
Looks like the app has many more languages in: https://github.com/nightscout/AndroidAPS/tree/master/app/src/main/res

**Comment by MilosKozak** [comment]
for translation just put URL as a string to resoureces. the rest can be resolved in crowdin

**Comment by Philoul** [comment]
@MilosKozak  and @xJoe 
> for translation just put URL as a string to resoureces. the rest can be resolved in crowdin

Yes, but I think we should improve that because crowdin links change according to translation and even sometimes according to doc "build" (we should use sometimes #id1 anchor whatever chapter's text name probably due to crowndin bugs...)
Links in crowdin are complicated to translate (in crowdin) because anchor inside document should be translated according to title translation to works, and if a title translation is modified, anchor's name changes too... (and most of time title translation is in another document...)

EN link `https://androidaps.readthedocs.io/en/latest/EN/Configuration/Config-Builder.html#local-profile-recommended`
de link : `https://androidaps.readthedocs.io/en/latest/CROWDIN/de/Configuration/Config-Builder.html#lokales-profil-empfohlen`
fr link : `https://androidaps.readthedocs.io/en/latest/CROWDIN/fr/Configuration/Config-Builder.html#profil-local-recommande`
...

It's very weak and complicated to maintain in crowdin when you translate doc (when you rename a chapter, you don't know if link is use somewhere else or not...), and it will be worse if we use crowdin links in AAPS...

My proposal would be to add in crowdin a hidden "links file" that includes untranslated keys that redirect to correspondant link (I don't know exactly how that could be done but I'm quite sure it's possible)
Something like:
`key="local-profile-recommended" link = "https://androidaps.readthedocs.io/en/latest/EN/Configuration/Config-Builder.html#local-profile-recommended"`

Translated in crowdin according to language by
`key="local-profile-recommended" link = "https://androidaps.readthedocs.io/en/latest/CROWDIN/de/Configuration/Config-Builder.html#lokales-profil-empfohlen"`
or
`key="local-profile-recommended" link = "https://androidaps.readthedocs.io/en/latest/CROWDIN/fr/Configuration/Config-Builder.html#profil-local-recommande"`

and everywhere (doc pages in crowdin or in AAPS, we could use stable links)
For AAPS side : 
`<string name="doc_header">https://androidaps.readthedocs.io/en/latest/EN/</string>`
`<string name="plugin_localProfile_help_url"  translatable="false">keyfile.html#local-profile-recommended</string>`

translated in crowdin (manualy or automatically) to
`<string name="doc_header">https://androidaps.readthedocs.io/en/latest/CROWDIN/de/</string>`
or
`<string name="doc_header">https://androidaps.readthedocs.io/en/latest/CROWDIN/fr/</string>`

For doc pages, we could use everywhere
`../keyfile.html#local-profile-recommended` (or any other key)

Finally to check if we have "dead links", we could manually open in browser keyfile.html file to check if all links work correctly

**Comment by xJoe** [comment]
Keep in mind that at present just one person is writting docs and any additional work cannot be done on my side.
Additionally it would make writing docs way more complex as before any change I'd have to make sure neither the general link page nor the links in the app are affected.

**Comment by Philoul** [comment]
@xJoe I know that writing documentation is a huge amount of work (I'm alone for translation and translating is easier than writing...)
Currently, each time you modify a chapter name, you have no easy way to know if an anchor is use somewhere else in doc. Even if I carefully translate and check links to anchors (with #xxxx), I'm sure there still remains several wrong links in french... and in all other languages due to translation, #id1 bugs... (I quickly navigated in german and spanish and I found one dead link and several wrong links in less than 5 min...)

You told me a few months ago that from times to times you checked all links in all pages (only in english I suppose) but manually and takes you a lot of time (using SnapLinksPlus ?)

For creation, I'm not sure it's more work if we put all the links in one place in one file  (it's only for "Anchor links", file names are stable and identical in all languages), but to check if all links works and ensure there are no broken links I'm sure having everything in one file is better...

For initializtion of this "key file" (.rst or .md I suppose), if someone can give me the correct syntax, I can generate a first version with existing doc files in english (I don't know in detail crowdin codification and how it works during build for creating html pages from .rst or .md files).
I can help too to convert, once key file created, existing links in the new syntax in english...

**Comment by Andries-Smit** [comment]
In the mark down the headers can have ids for example `## header {#my-header-id}` In the translations we could have the headers translated and keep the ID in English.  (Though I nut sure if .rts does support heading ids too)

The current doc URL do look a bit strange too take for example the URL `https://androidaps.readthedocs.io/en/latest/CROWDIN/de/Configuration/Config-Builder.html#lokales-profil-empfohlen`  the `/en/` should be the language selection. In the current repo all languages are placed under the English site. This is not how it recommended https://docs.readthedocs.io/en/stable/localization.html#project-with-multiple-translations
This also cause the search functionality to less use full as it results in many duplicated results from different languages. (Discussed in the https://gitter.im/AndroidAPSwiki/Lobby)

**Comment by xJoe** [comment]
Concerning setup reason probably @MilosKozak could tell.
My IT knowledge doesn't allow me to comment on anchor idea. From user point of view sounds good but I recommend to use a test setup first as we have different problems with the combination of github, RTD and Crowdin. Example:
Github: https://github.com/openaps/AndroidAPSdocs/blob/master/docs/EN/Configuration/OmnipodEros.rst#icons
RTD: https://androidaps.readthedocs.io/en/latest/EN/Configuration/OmnipodEros.html#icons

**Comment by MilosKozak** [comment]
Using links inside a page along with translations makes too much troubles. I'd avoid it for help pages

**Comment by Philoul** [comment]
> Github: https://github.com/openaps/AndroidAPSdocs/blob/master/docs/EN/Configuration/OmnipodEros.rst#icons
> RTD: https://androidaps.readthedocs.io/en/latest/EN/Configuration/OmnipodEros.html#icons

When I ran Linkcheck utility on master doc link (`linkcheck https://androidaps.readthedocs.io/en/latest`), I found several css error in build, that could explain this (see extract below for OmnipodEros page...)

```
https://androidaps.readthedocs.io/en/latest/CROWDIN/cs/Configuration/OmnipodEros.html
- (46:2) <link> => https://androidaps.readthedocs.io/en/latest/_static/css/theme.css (connection failed)
- (382:410) '*' => https://androidaps.readthedocs.io/en/latest/CROWDIN/cs/Configuration/OmnipodEros.html#id1 (HTTP 200 but missing anchor)
- (749:12) 'Troubles..' => https://androidaps.readthedocs.io/en/latest/CROWDIN/cs/Configuration/OmnipodEros.html#troubleshooting (HTTP 200 but missing anchor)
- (46:2) <link> => https://androidaps.readthedocs.io/en/latest/_static/css/theme.css (connection failed)
- (292:4) <img> => https://androidaps.readthedocs.io/en/latest/_images/Omnipod_Pod.png (connection failed)
- (616:8) <img> => https://androidaps.readthedocs.io/en/latest/_images/RileyLink_Statistics_Settings_1.png (connection failed)
```

> Using links inside a page along with translations makes too much troubles. I'd avoid it for help pages
> Simple 1 page per link from AAPS
> +index for browsing from docs

I'm agree there are lots of problem, but some pages are very long, and it's cool when you read the doc to to be able to directly reach a dedicated chapter with anchors (I think the necessity today to manually translate anchors according to translation is the main root cause of these issues, and having untranslated fixed keys to do that could improve it...)

**Comment by xJoe** [comment]
After I created Omnipod page from their Google docs Omnipod team decided to completely re-do the page on their own.

We need the links to headlines anchors as docs are too complex just to complex for just linking to a certain page. Even though some links do not work, most of them do.

**Comment by Andries-Smit** [comment]
@Philoul it is not possible to run link checker  on the production website. As the `readthedocs.io` is protected against to many requests. after x request it will no longer respond to protect it self against doss attaches. To do a full scan on the build documentation we probably have to run it in a local setup. (I failed to do so at short notice but ill give it an other try) Does anybody succeeded to make the docs run locally?

**Comment by Philoul** [comment]
@Andries-Smit I didn't know it was not possible, so I did it ;-) ... (`linkcheck https://androidaps.readthedocs.io/en/latest`), see synthesis I made in attached Excel file below
I manually checked yesterday in my browser 2 or 3 links detected with "Error 404" and I couldn't open them in my browser too (and I also checked one "missing anchor" and I opened the top of the page...). I think results are not so bad... (I didn't understand difference between "HTTP 404" error and "Connection failed" error ???)

I just had to check french doc with a second command (`linkcheck https://androidaps.readthedocs.io/en/latest/CROWDIN/fr`), probably because french doc is hidden (no links in main menu)

Linkcheck
(in Excel file, I removed all css error, because not the purpose of our discussion)
[Linkcheck.xlsx](https://github.com/nightscout/AndroidAPS/files/5795327/Linkcheck.xlsx)

**Comment by Philoul** [comment]
> We need the links to headlines anchors as docs are too complex just to complex for just linking to a certain page. Even though some links do not work, most of them do.

I completely agree with Achim, even if above synthesis is a bit scary, most of the links work (and I'm convinced we can quickly improve the situation in all languages if we could remove the necessity to translate anchors...)

**Comment by Andries-Smit** [comment]
To improve search and language links I opened a PR the related to this topic. https://github.com/openaps/AndroidAPSdocs/pull/959

**Comment by Andries-Smit** [comment]
For adding anchors that are language independent there is option.

For all links from the help button to the docs, we can add an extra language independent anchor
https://sublime-and-sphinx-guide.readthedocs.io/en/latest/references.html#use-a-custom-anchor

In rst file
``` rst
.. _help-extended-bolus:

Extended bolus
==============
```

For markdown we can leverage `eval_rst` https://recommonmark.readthedocs.io/en/latest/auto_structify.html#embed-restructuredtext
```` md
```eval_rst
.. _help-settings-aps:
```
  
## Settings in AAPS
```

**Comment by AdrianLxM** [comment]
To get a better overview over open topics for the upcoming release, I converted this to a draft PR (it had WIP in the header). Please feel free to convert it back at any time.

**Pull request closed without merging**
