### PR TITLE
Support for BYODA-G7 

### PR DESCRIPTION
**Pull request by rICTx-T1D**
- https://github.com/DiaKEM/dexcom-g7-aaps/tree/dev-g7
- https://github.com/DiaKEM/dexcom-g7-apk-patcher

### CODE REVIEW

**Comment by mxsrm** [comment]
will you merge this before next stable release Milos? Looks like straightforward code changes to me.

**Comment by mxsrm** [comment]
Any update here?

**Comment by MilosKozak** [comment]
remove agp downgrade
wiki documentation must exist

**Comment by rICTx-T1D** [comment]
> remove agp downgrade wiki documentation must exist

@khskekec can you change it, so we can make a new try to push

**Comment by khskekec** [comment]
@rICTx-T1D yes, i will take care of it.

@MilosKozak Where/How should I create the wiki page for this? What should it describe? General tutorial how to get G7 integrated into AAPS?

Kind regards

Selçuk

**Comment by vidschofelix** [comment]
> @MilosKozak Where/How should I create the wiki page for this? What should it describe? General tutorial how to get G7 integrated into AAPS?

Here, i guess: https://github.com/openaps/AndroidAPSdocs/tree/master/docs/EN/Hardware

**Comment by MilosKozak** [comment]
patching an apk in linux is out of possibilities of 99% of people
the rest can handle it in this form.
I'd wait for more friendly solution
And there is still AGP downgrade in this PR

**Comment by LuisPuertollano** [comment]
Hello,

It seems that a dexcom g7 patched app is beeing distributed. Is there any possibility to continue this pr? Thanks!

**Pull request closed without merging**
