### PR TITLE
[WIP] Autotune Plugin

### PR DESCRIPTION
**Pull request by Philoul**
Branch for testers, I propose to replace this huge PR (more than 550 commits and 66 files modified) by some little PR)
*********************************************************************************************************
It's this first time I think I have a working version of Autotune (see below compare results).
=> Until now tests are OK (AAPS results consistent with oref0 autotune plugin, the same after rounding)
=> Oref0 files used as reference are included in this PR (I can remove them of course)
=> I also included adapted version of oref0 to be able to run oref0 algo on exported files from autotune plugin (without NS queries).

For each autotune run you have a zip file with everything to be able to launch oref0, and 2 sub folders in log with all files in oref0 format exported for the last run.

Note you can have more gaps with autotune web for several reasons:
- Autotune Web don't take into account ProfileSwitches (All periods without TBR running are not included in autotuneWeb calculation...). These periods are included in current version of Autotune
- Absolute values for TBR sent to NS can have wrong values if converted from percent and accross several hours (they are not splitted so BR at Timestamp can be different than during all the duration of TBR)
- oref0 split TBR every 30 min for iob calculation (that can create some variation in iob calculation and some little amount of insulin can sometimes be ignored)
- In autotune plugin, I rounded all timestamp and duration to minutes (duration are rounded but not timestamp in NS)
- Rounding in js and kotlin can be different

You can see in screenshot below compare results between Autotune Plugin and oref0 algo with same input data and 5 days (oref0 on a virtual machine)
Autotune Compare

I also attached the 2 log files (generated with Autotune Plugin and oref0)
=> I tried to be as close as possible in log to be able to compare results
[autotune.2022-03-20-213315.log](https://github.com/nightscout/AndroidAPS/files/8312241/autotune.2022-03-20-213315.log)
[autotune.2022-03-20.log](https://github.com/nightscout/AndroidAPS/files/8312242/autotune.2022-03-20.log)

### CODE REVIEW

**Comment by vanelsberg** [comment]
WIP suggests there is still lots of work to be done. Bit this PR looks functionally very complete.

**Initial testing:**
* PR builds and installs OK. Autotune plugin can be selected and configured from Config Builder as expected.
* Manually starting autotune generates a suggested profile that can be selected for active profile.
* Automation has an additional option to schedule autotune.

Functionally Autotune seems to be complete and working as expected.
Profile suggestions based on the last 5 days look really good (need some days to see how it well it actually is doing)

@Philoul I think you did exceptional work. Tnx!
Will be testing this. Once fully tested and released I think this is going to be a wonderful addition to AAPS for many users to benefit from.

Minor bug:
On my test phone Autotune crashes AAPS when manually running Autotune for more than 7 days. I think this may be caused by either running out of resources or some timing/timeout problem. For now, I would suggest limiting the number of days to 5 days to prevent?

**Comment by Philoul** [comment]
Send me log please (better logcat stack of crash if you can).
I could run without problem with more than 15 days, maximum 30 days selected if I remember well, it could be linked to empty data for one day in your history, or no meal recorded...

Tell me if you can add one more day tomorrow without crash.

**Comment by Philoul** [comment]
You can also run autotune web starting the day that create crash and send me log file of oref0 autotune attached in mail received.

**Comment by vanelsberg** [comment]
Screenshot 2022-03-23 195516

Now can only repro this on the test phone which mirroring the main phone, feeding from NS.
On the main phone problem can no longer be reproduced. Just successfully ran autotune for 15 days

**Comment by Philoul** [comment]
> WIP suggests there is still lots of work to be done. Bit this PR looks functionally very complete.

I put WIP for tester mainly, on my side I have consistent results with Oref0 Autotune , but I didn't test all configuration (mmol, pump with Absolute rate, Combo Bolus without Fake TBR...) and I want to be sure I always get in all configuration consistent results with the oref0 version.
So tester should be very prudent.
I think user interface should probably be improved for result (replace text results by html formating...)

No unit test (only a draft to be able to compare some objects, but not enough to validate the plugin...)

**Comment by Philoul** [comment]
@vanelsberg Thanks for Logcat, crash fixed, can you try again on your dev phone to confirm 
(crash was because no BG values are recorded in your dev phone before 6 or 7 days ago...)

**Comment by Philoul** [comment]
I now have a second example (thanks @vanelsberg ) with another pump (Dash), another unit (mmol), and another insulin (FIASP) with 15 days, and again very very close results, the same after rounding...

[autotune.2022-03-24-215728.log](https://github.com/nightscout/AndroidAPS/files/8345936/autotune.2022-03-24-215728.log)
[autotune.2022-03-24.log](https://github.com/nightscout/AndroidAPS/files/8345937/autotune.2022-03-24.log)

**Comment by swissalpine** [comment]
Looks really good!
When I change "Number of days of data" (preferences) from 5 to 7 or from 5 to 3 the amount of "Tune days" doesn't change. It remains with the 5 days that are given.

**Comment by Philoul** [comment]
@swissalpine In prefetences you set default number of days, this default number will be used if you run autotune with automation, or the first time you open autotune a new day (without any run before), or just after a restart of aaps.
Note: for autotune, a new day starts at 4AM...

**Comment by swissalpine** [comment]
@Philoul Thanks for the clarification! It is a new experience that changing the settings does not lead to an immediate change. In fact, a restart will apply this setting.

**Comment by Philoul** [comment]
Provably a lot of things should be improved: I'm currently focussed on validation (safety: results should be consistent with oref0 algo, and no crashes).
Feel free to propose improvements...

**Comment by vanelsberg** [comment]
Very pleased with preliminary results if have seen for the past 3 days 👍 

Have AT configured to run for 1 day intervals using automation to set a new "Tuned" profile for AAPS once a day at 06:30h.
After running for the 3th day "Tuned" profile is "very close" to my usual profile in such a way that I can not conclude which off the two is "better". Fact is that the tuned profile seems to work quite good for me.

Decided to run AT this way for the coming 7 days or so, to see how it is converging to a stable profile.
Also very curious on how it handles my strong day-to-day sensitivity changes and problems with negative IOB buildup. Something that "autosense" was unable to handle.

**Comment by swissalpine** [comment]
I noticed the following, but maybe the following use of autotune is also not correct or my "life" with very changing insulin amounts is not made for that either.
When I run autotune (with 30 days), it suggests a profile increase of about 30%, which fits my autosense values (1.3). If I run autotune two more times after that, I find almost the same increase once more and a slightly lower one on the third run (total insulin: 16.46 (original) -> 20.3 (at1) -> 24.3 (at2) -> 26.3 (at3)).   This is an amazingly high basal for a person who uses an average of about 37 U of insulin (last week between 31.3 to 49.6 daily total) a day. It can't be due to lack of carbohydrate inputs, because I input everything per se, except rare hypo carbs.
I'm sure it's not your code, but a safety factor would certainly be useful in the original algorithm (e.g. basal max <= 50% TDD 7 days).
- - -
What is surprising is how fast my Jelly 2 calculates 30 days. Since my PC had two years ago needed significantly more time for a similar calculation ...

**Comment by kristinsmotz** [comment]
I'm testing this plugin and noticed a bug while trying to set a profile % automation. When I chose percentage profile, and went to set the wanted % and duration, I couldn't enter the correct dialog, instead it asked me "Run autotune?" with options OK or cancel. I did a screenrecording while reproducing. 

https://user-images.githubusercontent.com/71758682/160297525-63a49611-fdc1-4363-94fd-d3367da53eba.mp4

**Comment by Philoul** [comment]
@swissalpine  Start with 7 days and 15 days for your run and send me autotune-2022-xx-xx-xxxx.zip file (dedicated data and log file for autotune in your log folder).
I will check if aaps plugin give the same / consistant results with oref0 algo. (if possible with my latest commits done today)

**Comment by Philoul** [comment]
> I'm testing this plugin and noticed a bug while trying to set a profile % automation. When I chose percentage profile, and went to set the wanted % and duration, I couldn't enter the correct dialog, instead it asked me "Run autotune?" with options OK or cancel. I did a screenrecording while reproducing.

@kristinsmotz Fixed with https://github.com/nightscout/AndroidAPS/pull/1468/commits/0b8fc5ddbb91c5f3b48054492e7056cd2c1d3244
Thanks

**Comment by swissalpine** [comment]
Hi, here are the logs from today:
a) 7 days
[autotune_2022-03-28_06-40-46.zip](https://github.com/nightscout/AndroidAPS/files/8359733/autotune_2022-03-28_06-40-46.zip)
b) 15 days
[autotune_2022-03-28_06-51-11.zip](https://github.com/nightscout/AndroidAPS/files/8359732/autotune_2022-03-28_06-51-11.zip)
One week ago I was skiing in the alps with reduced basal ...
Thanks for your investigations!

**Comment by swissalpine** [comment]
O.K. There are differences in ISF and CR and really small differences in BR.

**Comment by Philoul** [comment]
Hello
Latest commit should improve consistency if you have a circadian ISF profile.

**Comment by Philoul** [comment]
With latest commits, Autotune can now update tuned profile into local profile plugin
You can select the input profile and the number of days in Autotune Automation Action

**Comment by Philoul** [comment]
@swissalpine on my latest commits, I improved result presentation, can you please send a screenshot with your small screen to see if it's ok ?

**Comment by swissalpine** [comment]
Thank you for your asking! It's very kind of you to keep an eye on the small screens!
Basically I don't like the Card View layout. It's a graphical gimmick that wastes valuable space on small screens - besides, the interface looked better to my taste before, at least on the Overview tab (here I already tweaked paddings and graph heights to make everything visible at a glance again). 
For actions fragment and your autotune tab it's ok and not problematic.
Screenshot_20220418-072718
Screenshot_20220418-072741
Screenshot_20220418-072755
Thanks for your incredible work on autone!

**Comment by Philoul** [comment]
Replaced by #1699

**Pull request closed without merging**
