### PR TITLE
[WIP] Style card views based on screen dimension

### PR DESCRIPTION
**Pull request by Andries-Smit**
Overview requires a different layout and dimensions for smaller screens; the cut-off point suggested at the moment is 400dp
Based on feedback in #1648 @swissalpine, feedback is required to see if this works for you

- Change cards dimensions based on screen width (padding, margin, corner radius)
- Move card style centralised (corner and elevation)
- Make card view in dark mode a darker than Material Design Default, with a slight grey border (it might require a small tweak later)
- Increased elevation of status lights for dark theme
- Removed some extra padding

image

### CODE REVIEW

**Comment by osodebailar** [comment]
You have additional seen that I posted a PR to set the overview cardviews ?

**Comment by Andries-Smit** [comment]
@osodebailar Ill wait with this PR. it also does not work the way I expected, anyway

**Comment by osodebailar** [comment]
> @osodebailar Ill wait with this PR. it also does not work the way I expected, anyway

Ok . But it looks ok.
Anyway , my fix for the overview fragment works in the way i want .

**Comment by swissalpine** [comment]
I assume that I should not test this at this time ...

**Comment by MilosKozak** [comment]
too much conflicts now

**Pull request closed without merging**
