### PR TITLE
Add Ottai CGM config

### PR DESCRIPTION
**Pull request by ottai-developer**

### CODE REVIEW

**Comment by MilosKozak** [comment]
Generaly OK. Before merge create PR with instruction to wiki https://github.com/openaps/AndroidAPSdocs

**Comment by ottai-developer** [comment]
> Generaly OK. Before merge create PR with instruction to wiki https://github.com/openaps/AndroidAPSdocs

I don't quite understand what you mean. I have to submit a change PR on the appropriate wiki？

**Comment by MilosKozak** [comment]
yes. Basically add new chapter for your CGM

**Comment by KORuL** [comment]
I use your @ottai-developer integration and application https://play.google.com/store/apps/details?id=com.ottai.seas, but the data does not go to AndroidAPS, I also rebuilt AndroidAPS and set a breakpoint and when new data appears in Ottai, your @ottai-developer application does not send a broadcast implicit intent to the system "info.nightscout.androidaps.action.OTTAI_APP" or "info.nightscout.androidaps.action.SYAI_TAG_APP"

I also made a mini application and registered a listener for these 2 events, Ottai regularly updated data from the sensor but did not send a single broadcast

**Pull request merged**
