### PR TITLE
Fix crash when open import settings in maintenance.

### PR DESCRIPTION
**Pull request by diyaps**

### CODE REVIEW

**Comment by MilosKozak** [comment]
the filter 3 lines up is not enough? still crashing?

**Comment by diyaps** [comment]
> the filter 3 lines up is not enough? still crashing?

The filter fixed the crash. But I found another issue. The sorting of the json files seems become incorrect. And the file on the top has a yellow version "v10.10.10.10". 
Without the 3 lines filter, there is no this issue. Please check the picture in the attachement.
_cgi-bin_mmwebwx-bin_webwxgetmsgimg__ MsgID=1755588150502786086 skey=@crypt_469a9a96_36623a154b902d3547bd542c199636af mmweb_appid=wx_webfilehelper
 
_cgi-bin_mmwebwx-bin_webwxgetmsgimg__ MsgID=1685562227301570704 skey=@crypt_469a9a96_36623a154b902d3547bd542c199636af mmweb_appid=wx_webfilehelper

**Comment by MilosKozak** [comment]
@Philoul how was it meant?

**Comment by Philoul** [comment]
I don't know, I never worked on this function...

**Comment by MilosKozak** [comment]
at the end more polishing was needed 
replaced by https://github.com/nightscout/AndroidAPS/commit/c8377edf9d7330246177d5fce31e5dc6d737f046

**Pull request closed without merging**
