### PR TITLE
UI: Omnipod Dash/Eros Page Upgrade

### PR DESCRIPTION
**Pull request by kenzo44**
Goal: Improve scannability and prioritize alerts

- Added the ability for users to tap and copy error codes

Before vs. After

Screenshot 2024-06-05 at 1 16 54 AM

### CODE REVIEW

**Comment by vanelsberg** [comment]
PR merges ok and is functional 👍 

Layout glitches?
- "Connection quality" and "Delivery Status" are somewhat indented (leading space)
- Some fields show empty value with "-", other do not.

**Comment by vanelsberg** [comment]
- Could we have the "Connection" section moved to in-between Bluetooth and Alerts?
- Pump icon (indicating active pump) only shows when swiping up. Proposing to move the pump icon to the top of the screen.

**Comment by vanelsberg** [comment]
Proposing section layout, which for me feels more logical:
- Pump icon
- Bluetooth
- Connection
- Alerts
- Delivery
- Firmware

**Comment by kenzo44** [comment]
> PR merges ok and is functional 👍
> 
> Layout glitches?
> 
>     * "Connection quality" and "Delivery Status" are somewhat indented (leading space)
> 
>     * Some fields show empty value with "-", other do not.

Fixed in the latest push

**Comment by MilosKozak** [comment]
well I want to keep the UI of AAPS unified as much od possible. When I thought about changing the layout in pump plugins, my idea was to create an interface/template for all pump drives to avoid code duplication ie. plugin would only specify the fields needed and provide data. The rest would be handled by AAPS core

**Comment by MilosKozak** [comment]
it would be nice task for using "Compose" in AAPS

**Comment by kenzo44** [comment]
> it would be nice task for using "Compose" in AAPS

100%. I noticed some pump pages used a different template.

According to the pump stats you posted, omnipod users are around 2.5k. For now, do you want to use this pr?

**Comment by vanelsberg** [comment]
@Kenzo44 Really appreciate your efforts in trying to improve the UI!

Personally, I have some problems with the current PR as is:
- It is not consistent with current UI in general. It should be part of a possible redesign of the UI, not just the pump TAB (for Omnipod only?)
- UI changes like this should at least have a formal functional review on user experience, consistency and (also) accessibility before implementing.

In addition:
- To me the layout is inefficient with screen resources (distracting layout items, adding the need for additional scrolling)
- I find the new tab more difficult to read where layout is distracting from the content which goal is showing current pump status.

My proposal would be to categorize this PR as a draft/concept for general improvement of the UI in general, possibly for next version 3.4.

**Comment by MilosKozak** [comment]
> > it would be nice task for using "Compose" in AAPS
> 
> 100%. I noticed some pump pages used a different template.
> 
> According to the pump stats you posted, omnipod users are around 2.5k. For now, do you want to use this pr?

If you change it to Compose with ideas how to share the code across AAPS I can accept it as an improvement (with expecting we will spread it to all drivers soon)

**Comment by MilosKozak** [comment]
> 
> * To me the layout is inefficient with screen resources (distracting layout items, adding the need for additional scrolling)
> * I find the new tab more difficult to read where layout is distracting from the content which goal is showing current pump status.

Agree

**Pull request closed without merging**
