### PR TITLE
Adrian/system carb timer

### PR DESCRIPTION
**Pull request by AdrianLxM**
This PR does 3 things:
### **1) Sets the system countdown timer if the user selected system notifications.** 

If not, it will use the Automation reminder.
This has the advantage, that it integrates well with the system notifications and some smart watches.
`scheduleEatReminder` always stays as `AutomationEvent` as it has other trigger events like deltas.
This should be at least a proper workaround for https://github.com/nightscout/AndroidAPS/issues/299

### **2) Refactors the carb reminder generation to an own class**
Can be used in other dialogs as well. E.g. for the carb dialogs

### **3) Adds a carb reminder to the carbs dialog as well**
Corresponding feature request: https://github.com/nightscout/AndroidAPS/issues/292

Video of system timer:
https://user-images.githubusercontent.com/9692866/107861295-41c28d00-6e45-11eb-8e31-a62f3476bd3e.mp4

Screenshot of new dialog
image

### CODE REVIEW

**Comment by MilosKozak** [comment]
definitely better than failing system dialog
I'd not use only for `key_raise_notifications_as_android_notifications` but all the time. can we do the same for bolus advisor to have it unified (ie start in 5 sec if condition met)?

**Comment by AdrianLxM** [comment]
@MilosKozak I've done the simplification to not use `key_raise_notifications_as_android_notifications`.

The alarm of the advisor - I'll think of something and add it in a separate PR.

**Comment by Philoul** [comment]
Just to be consistent with Wizard dialog, the checkbox is on the right of number picker in your proposal of carb dialog, and on the left (between "Time offset" label and number picker), in wizard dialog...
I think it's better if in both dialog the checkbox and associated icon are at the same place.

**Comment by AdrianLxM** [comment]
@Philoul coming up soon :) Thanks for the suggestion.
image

**Comment by Philoul** [comment]
just switch icon and check box and it will be perfect 😁

**Comment by MilosKozak** [comment]
tests are failing

**Comment by AdrianLxM** [comment]
@Philoul 
image

@MilosKozak nice catch, thanks. was only the test setup.

**Pull request merged**
