### PR TITLE
CWF Add TempTarget Management with TT Color

### PR DESCRIPTION
**Pull request by Philoul**
For feature request #2335

### CODE REVIEW

**Comment by Philoul** [comment]
To test it I updated a bit Analog Watchface and I replaced BGI view by TempTarget View below Carbs...
White, Yellow Green according to TT (only tested White and Yellow...)
=> Note that this will not work if you have Target-Low and Target-High

[Analog G-Watch_TT.zip](https://github.com/user-attachments/files/17880527/Analog.G-Watch_TT.zip)
CustomWatchface

**Comment by Philoul** [comment]
Green color when TT is adjusted by the loop works as expected 😉

**Comment by olorinmaia** [comment]
I can confirm this is working  :) I tried to modify AAPSV2 to display TT instead of BGI or Rig Battery, but I don't seem to be able to make it work. The watchface doesn't appear after uploading zip-file :)

**Comment by Philoul** [comment]
Check if Show Temp Target is enabled in preferences (within AAPS app in watch)

**Comment by Philoul** [comment]
Be carefull by default font is white if no TT is set, if divider has white background you will not see TT...

**Pull request merged**
