### PR TITLE
Wear OS improvements

### PR DESCRIPTION
**Pull request by Andries-Smit**
General improvements for Wear OS:
- Enable rotary input (Samsung watch 4 active bezel) 
- Add icons to the menu
- Add animation to menu
- Support back button in menu navigation
- Add titles in action grids (bolus, tempt, etc)

### CODE REVIEW

**Comment by dlvoy** [comment]
Hi @Andries-Smit, I am doing review & testing of your recent changes,
I've tested it on Galaxy watch 4 Classic using PL (Polish) locale which is a little bit longer 
but till now were fine, and with changes to menu layout there are some slight glitches:







_Screenshot are square, but displayed area is round, matching roughly circled logo in background_

1. Title of settings dialog should be centered
2. Action dialog titles - sometimes get cut out (in Węgle letters ę and g bottom)
3. Can you change layout of menu - to use round screen more optimally and display icon as left as possible, on round plain instead of inner square? Like on screenshot - (i) icon on Status item have lot of space on the left. Additionally - if possible - adjusting spacing and font size for item above & below main item to prevent word wrapping and getting cut out

Crown rotary input and menu scrolling works like a charm!

**Comment by Andries-Smit** [comment]
@dlvoy Thanks for the feedback, I will have a look.

**Comment by dlvoy** [comment]
Maybe changing list to behave like: https://developer.android.com/training/wearables/overlays/lists#curved-layout will help

**Comment by Andries-Smit** [comment]
@dlvoy 
1) The settings were not touched in the PR, they are not beautifully, maybe next time we can have a look at an alternative implementation.
2) Titles did get a bit more wiggle room. Tough long titles, hard to prevent from clipping, ideally it would be curved text, but that is only on SDK 31
3) I did rewrite the outdated WearableListView  into a WearableRecyclerView with the curved layout, and colour icons

image

**Comment by dlvoy** [comment]
Works like a charm! Thanks!
Retested on:
- Wear OS 3 (Galaxy Watch 4 Classic) - _screen 1&2_
- Wear OS 2 (Huawei Watch 2) - _screen 3_
- Square Wear OS 2 Simulator - _screen 4_

**Comment by MilosKozak** [comment]
Thanks to both of you!
@Andries-Smit do you have experience with Watch development. Used libs are really obsolete :(

**Comment by Andries-Smit** [comment]
@MilosKozak Just getting to know the topic. I will dive into this a bit more

**Pull request merged**
