### PR TITLE
WIP: Refactor and renew user interface

### PR DESCRIPTION
**Pull request by osodebailar**
This PR is primarily to introduce my work of a refactored a new designed user interface for AAPS.
Not ready to 100%, but only some little details and work missing.
Many thanks to @Rig22  for his design ideas and many of new icons.

The goal is to go on further with missing tasks,  to determine the essential things for implementing
all or the major things needed in AAPS.

Changes/Advantages of the new GUI are:

- all styles, colors and components changed to material design.
- light and dark mode ( night / not night )
- for the moment 21 night and 21 light themes are integrated
- theme option to choose a preselected background pic ( for some not all themes)
- change background color aand dialog background with color selector.
Header / bottom toolbar is present 
- reworked bottom toolbar
- reworked header which holds all necessary information including one click action to
  open the necessary dialogs 
- background blur effect for nav menu and the most dialogs.
- swipe refresh for some dialogs, pump dialogs for example to refresh data and save space.

For the developers:
- no hardcoded colors in fragment files and no more hardcoded colors in code.
- All colors work with the 3 color table colors.xml for default/night/not night mode
- the most color needed to colorize the gui are implemented as Attributes 
- in addition many icons can be changed with attributes.
- you can further informations of the things that are implemented, components, styles,
  colors: https://material.io/design

Further goals: 
- make the UI more perfect, stable and usable.
- extend attributes to also change dialog icons and other resources 
  for example via the different styles

Here are some screenshots as an example:

Screenshot_20210129-125156
Screenshot_20210129-125212 - Kopie
Screenshot_20210129-125212
Screenshot_20210129-125231 - Kopie
Screenshot_20210129-125231
Screenshot_20210129-125241 - Kopie
Screenshot_20210129-125241
Screenshot_20210129-125358 - Kopie
Screenshot_20210129-125358
Screenshot_20210129-125412 - Kopie
Screenshot_20210129-125412
Screenshot_20210129-125504 - Kopie
Screenshot_20210129-125504
Screenshot_20210129-125513 - Kopie
Screenshot_20210129-125513
Screenshot_20210129-125541 - Kopie

Screenshot_20210129-125552 - Kopie
Screenshot_20210129-125552
Screenshot_20210129-125556 - Kopie
Screenshot_20210129-125556
Screenshot_20210129-160615 - Kopie
Screenshot_20210129-160615
Screenshot_20210129-160625 - Kopie
Screenshot_20210129-160625
Screenshot_20210129-160733 - Kopie
Screenshot_20210129-160733
Screenshot_20210129-160742 - Kopie
Screenshot_20210129-160742
Screenshot_20210129-160821 - Kopie
Screenshot_20210129-160821
Screenshot_20210129-180313 - Kopie
Screenshot_20210129-180313
Screenshot_20210129-124423 - Kopie
Screenshot_20210129-124423
Screenshot_20210129-124451 - Kopie
Screenshot_20210129-124451
Screenshot_20210129-124501 - Kopie
Screenshot_20210129-124501
Screenshot_20210129-124511 - Kopie
Screenshot_20210129-124511
Screenshot_20210129-124528 - Kopie
Screenshot_20210129-124528
Screenshot_20210129-124536 - Kopie
Screenshot_20210129-124536
Screenshot_20210129-124543 - Kopie
Screenshot_20210129-124543
Screenshot_20210129-124602
Screenshot_20210129-124613
Screenshot_20210129-124631
Screenshot_20210129-124639
Screenshot_20210129-124650
Screenshot_20210129-124701
Screenshot_20210129-124714
Screenshot_20210129-124727
Screenshot_20210129-124753
Screenshot_20210129-124801
Screenshot_20210129-124827
Screenshot_20210129-124841
Screenshot_20210129-124916
Screenshot_20210129-124925 - Kopie
Screenshot_20210129-124925
Screenshot_20210129-124931 - Kopie
Screenshot_20210129-124931
Screenshot_20210129-124945 - Kopie
Screenshot_20210129-124945
Screenshot_20210129-125053 - Kopie
Screenshot_20210129-125053
Screenshot_20210129-125122 - Kopie
Screenshot_20210129-125122
Screenshot_20210129-125142 - Kopie
Screenshot_20210129-125142
Screenshot_20210129-125156 - Kopie

### CODE REVIEW

**Comment by Rig22** [comment]
Great job Andreas. :)

**Comment by MilosKozak** [comment]
**Good points:**
- conversion to material design
- extracted colors
- swipe refresh

**Neutral points:**
- someone can like new layout, someone not (I personaly don't like)
- BW icons & buttons. I personaly don't like it because I use colors for navigation in app
- Light and dark mode (if this doesn't mean add too much code)

**Negative points:**
- PR is too large, impossible to review
- There is too much unneeded changes in PR (lot of trash files, formating changes etc ...) (500+ files)
- stability
- I don't think bottom left & right menu is better. Having plugins in both is confusing.
- Large icons on top of pump plugins


**Conclusion:**
The main point I have is that these changes would be nice for MP3 player, social network application etc. But it's absolutely not necessary for an APS system. I don't belive it's necessary to have a Ferrari or queen Anna as a background.
It brings too much complexity along with many places for potential bugs.
The wide customizatibility is double-edged. Someone may really enjoy it but the result is usually not better than some predefined set of colors prepared by designer.


**Finaly:**
I don't want break your effort. I'm sure there are people who like it. I don't have problem if this exists if you are able to support people using it. But I don't think this should be in mainstream.
What I can do is accept changes from good points as a separate PRs. I'm able to accept PRs which improve the code and may help you with future ingeration of changes to your fork

The rest we can leave here for discussion ....

**Comment by StephenBrown2** [comment]
I can second most points made by @MilosKozak, though in my opinion BW icons & buttons are in fact a strong negative, as a consistent color theme for these icons is important to avoid confusion.
Also, a background image is an unnecessary feature, potentially distracting from the graph information which is already a bit cluttered and needs to be as clear as possible.

If this PR can be shrunk to a reasonable size with all the extraneous changes removed, I think it would be more welcomely received. In summary, wholeheartedly second Milos' Final paragraph. Separate out into smaller PRs with the conversion to material design, extracted colors, and swipe refresh, and the redesign can start from there.

Smaller incremental changes are better.

**Comment by AdrianLxM** [comment]
I'm closing this in favour of a PR that only does dark/light theme switching.

**Pull request closed without merging**
