### PR TITLE
UI: Improved button accessibility in bolus wizard

### PR DESCRIPTION
**Pull request by kenzo44**
Solution https://github.com/nightscout/AndroidAPS/issues/3210

- Enabled/disabled state is obvious
- Added spacing between buttons and cancel button to prevent accidental taps

### CODE REVIEW

**Comment by MilosKozak** [comment]
I don't like this predefined material design. In anyone able to create custom toggle button?

**Comment by kenzo44** [comment]
@MilosKozak I can look into it. Initially, I was using custom buttons but switched to the default material look since it was faster.

What kind of design do you have in mind?

**Comment by MilosKozak** [comment]
This looks like a tab we use elsewhere
I could imagine border around and change backgroung on toggle or something similiar

**Comment by kenzo44** [comment]
@MilosKozak please review. I have updated the look of the buttons for both light and dark themes.

**Comment by MilosKozak** [comment]
I like it now!

**Pull request merged**
