### PR TITLE
Wear always on simple UI

### PR DESCRIPTION
**Pull request by Andries-Smit**
The possibility to show a basic UI with just BG, direction and time was added in PR #1082 
This PR is an extension of the PR above, to show a simplified UI in the "always-on" / "ambient" mode. 
And it includes some optimisation in the onDraw & update function to optimize battery usage.
The simplified UI is optional and can be configured through the watch face settings 
"off, during charging, always on, always on and charging)

### CODE REVIEW

**Comment by vanelsberg** [comment]
Test OK!

Always On and general functionality of the watch faces tested ok and stable on Samsung Watch 4 for several days.
Specifically tested for power usage. "Always on" does use more power as is to be expected:

Under normal lighting conditions the Watch 4 (Classic 46mm) did not show unexpected power drain, lasting 24 hrs on a full charge which imho is quite decent!

**Comment by dlvoy** [comment]
Despite it was just merged, i have some review / questions / sugestions :D

- `watchface_simplify_ui_name` is not getting translated after merge by Crowdin, @MilosKozak maybe it can be somehow configured to include/support for `wear/src/main/res/values/arrays.xml` on Crowdin?
- when i was looking for that configuration option, **Simplify UI** was not obvious for me - i mean that it will have anything to do battery saving / always on mode or charging mode. 

Tested on Galaxy Watch 4 and works awesome, will retest on Huawei with older wearos too.

**Comment by Andries-Smit** [comment]
@dlvoy the `Simplify UI` was the working title, it did stick. Any inspiration or suggestions to iterate over?

**Comment by dlvoy** [comment]
hm... _Power Saving UI_? 

or _Power Saving_ if it grows to have more options - like split During Charging option from Always on option -  curent switch controlls two boolean options by making one 2x2 perm, which is fine from dev perspective (simple, one option) but harder from UX perspective

**Pull request merged**
