### PR TITLE
Export CSV for User Entries

### PR DESCRIPTION
**Pull request by Philoul**
I worked on it on a seperate branch because not sure of Architecture to do properly that export
- I tried to make synergies with Maintenance Export Preferences

After verification csv export is done correctly on my dev phone (I can see these files from the phone, but not from my computer) I just have to move them to another folder and it works.
@MilosKozak Can you review this proposal ?

### CODE REVIEW

**Comment by MilosKozak** [comment]
what is the export path now?

**Comment by Philoul** [comment]
AAPS/exports (path is defined in companion object of PrefFileListProvider)

**Comment by Philoul** [comment]
Do you planned to add other csv exports from AAPS or should we complete UserEntry with all missing events (Smb, entries from automation rules, extended bolus...) ?

**Comment by Philoul** [comment]
I propose to close this PR and merge it in #393:
- I removed Password confirmation
- Export added in Maintenance fragment
- Cleaning made
- See Screenshot below and zip file attached with 2 exports (first in french mg/dl, the second in English / mmol), (UTF8 codification for french language has to be selected in Excel)

Screenshot_20210308-213832


[UE_csv_export.zip](https://github.com/nightscout/AndroidAPS/files/6104044/UE_csv_export.zip)

**Comment by Philoul** [comment]
Merged in #393

**Pull request closed without merging**
