### PR TITLE
Correction xDrip -> xDrip+

### PR DESCRIPTION
**Pull request by xJoe**

### CODE REVIEW

**Comment by MilosKozak** [comment]
hmmm this will lead to many unapproved strings.
I'll merge in next version

**Comment by guydavies** [comment]
I know that Crowdin is the process, but is there not a way to do a global
search and replace along the lines of s/xDrip /xDrip+ /g and then set all
those changed translations to approved automatically?  It would definitely
be a useful feature request to Crowdin if it's not possible.

**Comment by xJoe** [comment]
That's true. I can understand your point, @MilosKozak.

**Comment by MilosKozak** [comment]
@AdrianLxM touched the same string so I merged this now

**Pull request merged**
