### PR TITLE
Improve Data Layer Foreground Service channel notification

### PR DESCRIPTION
**Pull request by olorinmaia**
This will make notification channel less intrusive. It will not pop up, make sound or vibrate when using complications. Also not add a dot on watch screen making you think you have an unread notification.

I've also added text for translation for both title and text describing notification. I'm not entirely sure if it's needed, but I added information about how to hide it, since I believe users may want to do so. As far as I have tested complications work allthough notification channel is hidden.

Improves issue described in https://github.com/nightscout/AndroidAPS/issues/3143

I've tested this on Samsung galaxy watch 4. Would be nice if someone with other type of wear os watches also could test this PR.

### CODE REVIEW

**Comment by mk89pwnz** [comment]
So if I want to have this now I need to merge this change to my fork? Nice to see this fixed.

**Comment by M1Sports20** [comment]
> So if I want to have this now I need to merge this change to my fork? Nice to see this fixed.

Yes, I would just cherry-pick the commit on your branch.
`git cherry-pick fe450757eb1789eebb88d231fc391a47e8c05c4d`

**Comment by mk89pwnz** [comment]
is this only in dev or merged to 3.2.0.4?

**Comment by M1Sports20** [comment]
Looks like its only in dev right now:
`% git branch -a --contains fe450757eb1789eebb88d231fc391a47e8c05c4d

remotes/origin/dependabot/gradle/dev/com.android.tools.build-gradle-8.4.1
remotes/origin/dependabot/gradle/dev/com.android.tools.build-gradle-8.5.0
remotes/origin/dependabot/gradle/dev/com.google.gms-google-services-4.4.2
remotes/origin/dev
remotes/origin/l10n_dev
remotes/origin/revert-3202-develop/automation-day
remotes/origin/unifydisf
`

**Pull request merged**
