### PR TITLE
Add Possibility to adjust Correction in Percent in Wizard

### PR DESCRIPTION
**Pull request by Philoul**
This possibility is regularly requested in issues (https://github.com/MilosKozak/AndroidAPS/issues/2462, #300, #977), what do you think of this proposal...

The Idea is to only add a CheckBox in current WizardDialog to select Units for correction (U or %) and to have an automatic convertion between both:

Current correction in Unit : CalculatedBolus = ( ∑ InsulinFromXxx + insulinFromCorr ) * PercentageFromSettings
Additional correction in % : CalculatedBolus = ( ∑ InsulinFromXxx ) * PercentageFromWizard
- Default value for PercentageFromWizard = PercentageFromSettings

When we switch from U to % (or % to U), CalculatedBolus remains identical, you immediatly see the global correspondence between both units see screenshots below:
- Deliver this part of bolus is set to 80% in my preferences for screenshots below (it works fine for standard days but before sport training, period of resistance, I generally adjust percentage and I think it's more complicated with Units, but for other reasons Units are easier than percentage to make corrections...)
- When I enter a correction in one unit (U or %), it is automatically converted in the other unit if I check or uncheck the box, then I can adjust value in selected unit
- Min/Max for percent is set to 10% to 250% (hard coded but these values can be added in Constant file and of course be changed)
- InsulinFromCorrection is set to 0.0 if percentage unit is selected
- Last selection of units (% or U) is memorized
- default value for percentage is the value set in preferences

image

Default values when you open wizard (according to last selection)
image

### CODE REVIEW

**Comment by Andries-Smit** [comment]
For users that will not use this feature, will the checkbox be hidden, just like the blue text? (Preference: General > Overview > Advanced > Deliver this part of the bolus wizard result [%])

**Comment by Philoul** [comment]
We can add some new parameters in Advanced settings of Overview but @MilosKozak doesn't want too many settings to not fall into "xDrip syndrome", so I prefer other solutions without additional settings...

The other idea would be to propose a short click on wizard button to have a very simplifed User Interface, and a long click with full interface...

Something like that with a Short Click (Photoshop coding, sorry for french interface...)
image

We can also memorize last selection of Advanced settings to show Simplified or advanced by default according to user selection on short click, same as View detailled information...

**Comment by Philoul** [comment]
@Andries-Smit 
> For users that will not use this feature, will the checkbox be hidden, just like the blue text? (Preference: General > Overview > Advanced > Deliver this part of the bolus wizard result [%])

You are right, if percentage is not set in preference We don't see le blue box it in WizardDialog, So I have to fix that

**Comment by avereha** [comment]
Something that we learned in https://github.com/nightscout/AndroidAPS/issues/976 is that if we give people too many (small)checkboxes, they are eventually going to click on them, even if by mistake.

If a user decides to use this feature, are they always going to use percentage correction(or absolute values) or they will need the ability to switch between percentage and absolute values on each action? If they always want to use one way or another for the correction, maybe a setting would simplify this dialogue a bit.

While I don't know exactly how we could make this better, I wanted to share that adding more options to a dialogue that already has a lot of options and is used often can lead to mistakes.

**Comment by Philoul** [comment]
> If a user decides to use this feature, are they always going to use percentage correction(or absolute values) or they will need the ability to switch between percentage and absolute values on each action? If they always want to use one way or another for the correction, maybe a setting would simplify this dialogue a bit.

I don't know, some users prefer Unit, but the question to also have % was asked several times

> Something that we learned in #976 is that if we give people too many (small)checkboxes, they are eventually going to click on them, even if by mistake.

I think there are no risk of mistake, because when you click on it, it doesn't change the result of calculated bolus, it only change and convert the unit of correction.
- I set 80% in my settings, but with Unit, I never know when I adjust Correction (especially positive value), if I'm still below 100% or above, I find usefull to immediatly check (or make adjustment quicker) to switch from U to % or on the other direction

> While I don't know exactly how we could make this better, I wanted to share that adding more options to a dialogue that already has a lot of options and is used often can lead to mistakes.

In wizard, I never use several fields : BG value (it's in overview in background, Profile selection),
My photoshop picture (before working on development) was proposals to simplify User Interface (without any additional settings...)

**Pull request closed without merging**
