### PR TITLE
Replace Loop Menu by a dialog

### PR DESCRIPTION
**Pull request by Philoul**
First version of "Loop Dialog" to replace loop menu in overview.
I created 2 new icons (see screenshots below)
- one used for both "enable loop" and "resume loop" (green triangle inside the closed loop green icon)
- a second for reconnect pump

Other points
- Validation popup (Ok/Cancel) is only shown if short click on apsmode icon (idem current version with menu)
- Only Cancel button in bottom of dialog (size of dialog adjusted accord to current status)
- I hope the dialog updates when the status of the loop changes (i.e. if we open dialog just before the end of disconnection) (not tested)

@MilosKozak What do you think of this first version ?
=> Should I update dialog icon and header with current loop icon / status ?
=> Other improvements (headers, dividing lines, icons...) ?

Screenshot_20201226-173849_AndroidAPS

### CODE REVIEW

**Comment by Philoul** [comment]
I added a commit to update "loop header" (forgotten in my first version)
Now the fixed text "Loop" you can see in my screenshots is replaced by "Enable loop" or "Disable loop"

**Comment by MilosKozak** [comment]
i'd add closed/open switching with so much space availeble now

**Comment by MilosKozak** [comment]
use Jetpack instead of `import kotlinx.android.synthetic.main.dialog_loop.*`

**Comment by MilosKozak** [comment]
old code is not removed

**Comment by Philoul** [comment]
See result with Close/LGS/Open switching

Screenshot_20201227-152832_AndroidAPS

**Comment by MilosKozak** [comment]
👍

**Pull request merged**
