### PR TITLE
Pressing 'clear filter' when filter is empty closes preferences

### PR DESCRIPTION
**Pull request by twain47**
Tweak based on feedback.

It is easy to end up pressing the 'X' as a close button for preferences so make it work as that as well if filter text is empty.

### CODE REVIEW

**Comment by osodebailar** [comment]
Whats about to change the edit textfield with an material textfield. So you need no code to clear the textfield with own code . And from the UI aspect its look ok a little bit better.
in my GUI fork i changed it to:

 <LinearLayout
        android:id="@+id/notes_layout"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginTop="8dp"
        android:orientation="horizontal">

        <com.google.android.material.textfield.TextInputLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            style="@style/Widget.MaterialComponents.TextInputLayout.OutlinedBox.Dense"
            android:hint="@string/filter"
            app:endIconMode="clear_text">

            <com.google.android.material.textfield.TextInputEditText
                android:id="@+id/pref_filter"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_marginStart="10dp"
                android:layout_marginEnd="10dp"
                android:layout_gravity="center_vertical"
                android:layout_weight="1"
                android:autofillHints="@string/filter"
                android:gravity="start"
                android:textStyle="bold"
                android:inputType="text|textCapSentences" />

        </com.google.android.material.textfield.TextInputLayout>

    </LinearLayout>

Screenshot_1606291662
Screenshot_1606291650

**Comment by twain47** [comment]
@osodebailar 
That is much neater - are you putting in a PR or is that change only on your branch?

**Comment by twain47** [comment]
@osodebailar 

`The style on this component requires your app theme to be Theme.MaterialComponents`

My android development experience isn't really up to following that - it sounds like a significant change to the whole project? Or is it trivial and you can point me at where to change it?

**Comment by osodebailar** [comment]
> @osodebailar
> 
> `The style on this component requires your app theme to be Theme.MaterialComponents`
> 
> My android development experience isn't really up to following that - it sounds like a significant change to the whole project? Or is it trivial and you can point me at where to change it?

Thx for info.
I will have a look and if possible i will change for further the whole project to material.

And yes my gui is a whole rework and totally based on material component.

**Comment by osodebailar** [comment]
@twain47 
i made a new pull request. 
you can see the differnces and you can test if all fragments are workinng. 
https://github.com/nightscout/AndroidAPS/pull/83

**Comment by twain47** [comment]
@osodebailar Thanks! This has been really useful.

I've updated this pr with a slightly modified version of yours.  Playing around I discovered we don't have to update styles.xml after all as long as we don't use `style="@style/Widget.MaterialComponents.TextInputLayout.OutlinedBox.Dense"`.  Not using that also results in a style more consistent with the rest of the current AAPS.  Probably best to leave global style changes to another PR.

Screenshots of how it now looks.

**Comment by osodebailar** [comment]
> @osodebailar Thanks! This has been really useful.
> 
> I've updated this pr with a slightly modified version of yours. Playing around I discovered we don't have to update styles.xml after all as long as we don't use `style="@style/Widget.MaterialComponents.TextInputLayout.OutlinedBox.Dense"`. Not using that also results in a style more consistent with the rest of the current AAPS. Probably best to leave global style changes to another PR.
> 
> Screenshots of how it now looks.
> 
> 
> 
> 

I have made the pr to change the style and therefore i think it is not a problem to do that.

Additional in the next  i will prepare my GUI rework as an PR.

**Pull request closed without merging**
