### PR TITLE
Update3.0

### PR DESCRIPTION
**Pull request by rosscortb**

### CODE REVIEW

**Comment by jbr7rr** [comment]
What the heck are you doing man ?

**Comment by rosscortb** [comment]
> What the heck are you doing ?
WHat do you mean?

**Comment by jbr7rr** [comment]
> > What the heck are you doing ?
> > WHat do you mean?

You keep opening these pointless PR's that is wasting time

**Comment by rosscortb** [comment]
I'm trying to make a change to my forked version, but struggling since
update. Sorry.

**Pull request closed without merging**
