### PR TITLE
enablebolusadvisor_summary

### PR DESCRIPTION
**Pull request by xJoe**
Few more details to make it easier to understand without reading docs.

### CODE REVIEW

**Review by rICTx-T1D — COMMENTED** [review]
@xJoe It is possible to change here, but I think many translators has translate this in their own language. No algorithm will reminder the translators to correct this.

**Comment by xJoe** [comment]
I am aware of this as I manage AAPS docs in Crowdin. But change of the original string will inform all translators that they have to have a look at this string.

**Comment by rICTx-T1D** [comment]
> But change of the original string will inform all translators that they have to have a look at this string.

That's new for me, ok I learned :-)

**Comment by xJoe** [comment]
There is no direct info by mail but Crowdin shows that something is new or changes. This is especially obvious if language was at 100% before.

**Comment by MilosKozak** [comment]
create new PR based on dev. this one is editing gradle too

**Comment by xJoe** [comment]
@rICTx-T1D sent you a message on gitter concerning watchface for docs.

**Pull request closed without merging**
