### PR TITLE
Dev quick wizard2

### PR DESCRIPTION
**Pull request by radicalb**
EDITED: 14.11.2023
- QuickWizard edit dialog completly refactored (new look)
- Bolus and Basal IOB joined together with "Positive only" option
- QuickWizard list - ADDED: run any QW using long press on quick wizard list item (all previouss navigation paths/actions remained unchaged, partly implementing **Issue #1270**)
- Fixed bug with deleting multiple QW entries (position/index of still to be deleted QW need to be shifted to left when previous QW is deleted).
- Extedned carbs in QW
- Carb time - delay & alarm in QW
- All functions supported in Wear too
- Superbolus option visible only if superbolus is enabled in Preferences
- Superbolus in qw from wear disables loop/zero basal for 2h (same as from phone)
- QW can be saved only if carbs are higher than 0 OR eCarbs are in use and higher than 0. 
- Corrected margin of Title text to not go over QW image on left side with longer translations.

### CODE REVIEW

**Comment by Philoul** [comment]
Global much better than before, great.

2 comments:

1) Within Calculator. we don't "disable" iob checkBox when Cob is checked (all checkbox are always enabled), we automatically uncheck cob if iob is unchecked, and we automatically check iob when cob is checked.
I think this simplify UI and allow one click less if you want to uncheck everything...

It's also strange to have positive only enabled when It's linked to iob that is disabled...

2) Other subject, why an underlined text field and slider for percentage, when everywhere else it's the standard + and - textbox (within this screen and also within Calculator for the same parameter) ? 
For consistancy I would keep + and - textbox for percentage

**Comment by radicalb** [comment]
Updated design:

1_b
1_c
1_d
1_newD1

**Comment by olorinmaia** [comment]
Since quick wizard sync to AAPSClient I strongly recommend keeping device options. I don't want quick wizard to show in AAPSClient for caregivers at school, since there is no option to hide it within AAPSClient.

If option is to be removed, a new option that allows Quick wizard button to be showed in overview screen (like Carbs, Insulin, treatment etc.) needs to be added.

**Comment by radicalb** [comment]
@olorinmaia I don't use the client. As I understand it it's visual thing only on client, so no harm if someone is trying to push the button. Are  qw syncronized between the main app and client? Otherwise if you don't want to see it, you can just remove qw entries in client? 🤔

**Comment by olorinmaia** [comment]
> @olorinmaia I don't use the client. As I understand it it's visual thing only on client, so no harm if someone is trying to push the button. Are  qw syncronized between the main app and client? Otherwise if you don't want to see it, you can just remove qw entries in client? 🤔

You can remove it from AAPSClient but it will sync back. Believe i have tried 😅

You can hit the QW button from AAPSclient and bolus and carbs are registered, some users fail to read or understand warnings. But not delivered by pump. It is this problem im afraid of and thats why we need to be able to hide QW button in AAPSClient. Either by setting in QW itself or in overview > button

**Comment by radicalb** [comment]
@olorinmaia just to clarify. Client works as wear? So in previous build if you selected only phone, quick wizard wasn't visible in client?

**Comment by olorinmaia** [comment]
> @olorinmaia just to clarify. Client works as wear? So in previous build if you selected only phone, quick wizard wasn't visible in client?

No. AAPSClient works just as AAPS. Only difference is that if you delete a QW from AAPSClient, it wont delete same QW in AAPS. The deleted QW will only sync back to AAPSClient in time.

So only way not to show QW in AAPSClient today, is to select only wear in QW settings. A new setting in overview > button would fix this.

**Comment by radicalb** [comment]
@olorinmaia but than you don't have quickwizard button on your main AAPS phone either. What is the point of having QW anyway? Do you change settings in quickwizard edit dialog every time from all to wear?

**Comment by olorinmaia** [comment]
> @olorinmaia but than you don't have quickwizard button on your main AAPS phone either. What is the point of having QW anyway? Do you change settings in quickwizard edit dialog every time from all to wear?

We use QW from AAPS wear. This is also most practical atm since you can show up to 4 QW at a time in wear. Like I said, we have to hide QW in AAPS phone so it can be hidden in AAPSclient phone, to solve one problem we create a new. But since we can use QW from AAPS wear it's "OK".

Now if you remove the option to choose device in QW settings, I have a problem! I hope you understand now?

**Comment by radicalb** [comment]
@olorinmaia I understand now. Will try to find some way to reintroduce device selection back to QuickWizard edit dialog. But it has to be such it doesn't have to much effect on qw edit dialog look.

**Comment by olorinmaia** [comment]
> @olorinmaia I understand now. Will try to find some way to reintroduce device selection back to QuickWizard edit dialog. But it has to be such it doesn't have to much effect on qw edit dialog look.

Or instead even better, add a new setting in Preferences > Overview > Buttons > Quick Wizard (show/hide toggle. default = on). If this setting is introduced, you can decide to show QW in AAPS phone, but decide to hide it in AAPSClient phone. Adding it back in QW settings we are back to square one, but that is better than removing it.

**Comment by radicalb** [comment]
Reintroduce device options. Visible only if wear is active. Just two checkboxes with phonne & watch background. Default both on.

1_deviceOption

**Comment by MilosKozak** [comment]
image
it doesn't fit screen well

**Comment by radicalb** [comment]
@MilosKozak shortened the strings (same as BolusWizard, e.g. Use temporary target -> TT), but used same string names as before. Will use BolusWizard strings directly istead, so translations will work correctly. Will do a new commit &push in tomorrow.

**Comment by radicalb** [comment]
Screenshot_20231028_211937_xx

@MilosKozak

**Comment by olorinmaia** [comment]
I think I found a small bug
1) I can't create a QW with all boxes unchecked.  "BS" is impossible to uncheck.

Possible improvement:
1) When using a QW with eCarbs maybe the information about eCarbs being added should show in the confirmationbox before pressing OK to bolus?

Layout is a nice upgrade. Great that we can add eCarbs. Great that you can bolus the other QW by longpressing!

**Comment by radicalb** [comment]
1_bolusWizzardECarbs

@olorinmaia I can uncheck all the checkboxes in edit QW dialog. Implemented info about ecarbs in confirmation box as suggested.

**Comment by olorinmaia** [comment]
I haven't build a PR branch before but i used New project from version control and added your repo then checked out pr branch and build apk.

I can uncheck it also. But when i click ok and open QW again it's still checked.

If my apk is broken ill try to rebuild.

**Comment by radicalb** [comment]
> I haven't build a PR branch before but i used New project from version control and added your repo then checked out pr branch and build apk.
> 
> I can uncheck it also. But when i click ok and open QW again it's still checked.
> 
> If my apk is broken ill try to rebuild.

There was bug in saving of use BG ckeckbox. Now it's fixed. Thx

**Comment by radicalb** [comment]
1_qw2_carbTime

Added carbtime and alarm option to QW. Can be usefull for some users.

**Comment by olorinmaia** [comment]
Some more feedback from me! First I'm not sure there is needed to add lesser used functions to QW settings. QW for me is stuff you bolus everyday. Personal opinion though :) Complexity increases because wear-app compatibility also must be added for new options. 

The following doesn't work in QW in wear. Users would expect that all choices in QW settings apply to wear as well when able to select them. Else you get different result using wear vs phone.
* Carb time
* Extended carbs

Improvements: 
* Superbolus doesn't work if Superbolus is deactivated in AAPS, hiding option for it in such a case would be an improvement of current QW settings. 
* Superbolus also deactivate loop for 2h if QW is used in AAPS, but not if used in wear. I haven't used Superbolus so not sure if it is a bug or not.
* Some comments on possible improvements on the layout on picture below :) 
image

**Comment by radicalb** [comment]
@olorinmaia thx for all information. Will try to set up the wear app on my wife's watch and see what can I do.

**Comment by radicalb** [comment]
@olorinmaia Extended carbs, carb time & alarm now working from Wear. Same for disabling loop/zero basal for next 2h after superbolus. If superbolus is not enabled, checkbox is hidden in edit qw dialog. But still need some work on design. Will try with one collumn design, because otherwise is hard to get some nice design for diferent sizes and especially for diferent translations (some are very long).

**Comment by radicalb** [comment]
New look.

newQW2

**Comment by radicalb** [comment]
qw2

**Comment by radicalb** [comment]
Meal alarm checkbox left-to-right orientation.
ltrM

**Comment by radicalb** [comment]
@olorinmaia did you check and test last version maybe?

**Comment by olorinmaia** [comment]
> @olorinmaia did you check and test last version maybe?

Tested abit now :) Visually it looks great! I tested every function in AAPS to be working as expected.

There are some problems with wear though. Bolus calc in wear stops working after running one QW calculation, and  then none of the QW tiles work. I can seem to get one calculation off, then it stops working. See picture for what QW tiles I'm testing with.  I noticed carbs didnt get added when I managed to get one QW calculation off from wear. If I restart AAPS it starts working for one calculation then stops again. Issuing TT e.g. works still. But not bolus calcs. I tried restarting watch also.

image

Logs:
[AndroidAPS_LOG_1700687209094.log.zip](https://github.com/nightscout/AndroidAPS/files/13444314/AndroidAPS_LOG_1700687209094.log.zip)

**Comment by radicalb** [comment]
@olorinmaia thx for all the input. Somehow I didn't noticed all the bugs coming in when solving different problems. I fixed all the bugs you noticed and almost produced another one 🙈. I would really need your help another time to check if everything is working fine now (already did it myself and it looks ok).

**Comment by olorinmaia** [comment]
@radicalb Excellent work :) I can only imagine when doing larger changes as this that some bugs can occur. It's impossible to single out everything yourself so don't worry. I'm far behind in the coding department, but I contribute in any way I can ;)

I can't find any new issues. I tested everything both in AAPS and wear.  A big improvement, both visually and a few new features to QW. @MilosKozak Could you also have a look?

**Comment by radicalb** [comment]
@MilosKozak I think pull request is ready for merge. Merry Christmas!

**Comment by vanelsberg** [comment]
> 2\. For consistancy I would keep + and - textbox for percentage
Yes, please.

**Pull request merged**
