### PR TITLE
Fix Dash historyIds

### PR DESCRIPTION
**Pull request by avereha**
Before this change, we used `ULID` for history Ids.
For `pumpId`, we would take the entropy part of the history id.

It turns out that on some phones the default Random() implementation does not have enough entropy and we are getting duplicate values.
Should fix https://github.com/nightscout/AndroidAPS/issues/1597

After update, the Dash history will be empty.

### CODE REVIEW

**Comment by jbr7rr** [comment]
Will this fix https://github.com/nightscout/AndroidAPS/issues/1597 ? Or is this a separate issue? I'm currently looking into that one but have been unable to pinpoint the exact issue there.

**Comment by avereha** [comment]
@jbr7rr : yes, I think so!

**Comment by vanelsberg** [comment]
> It turns out that on some phones the default Random() implementation does not have enough entropy 

Wow. Nice find Andrei.
Will test!

**Comment by vanelsberg** [comment]
> After update, the Dash history will be empty.

@avereha Also lost the active Pod (which was beyond 72 hours anyway)
Could that be or is this "unexpected"..

**Comment by avereha** [comment]
This is very possible!
I changed the Dash configuration.

**Pull request merged**
