### PR TITLE
PR3463 unattended settings export (draft)

### PR DESCRIPTION
**Pull request by vanelsberg**
This PR enable unattended exports
See https://github.com/nightscout/AndroidAPS/issues/3461

### CODE REVIEW

**Comment by olorinmaia** [comment]
Built PR OK and testing features. So far very good.

**Comment by vanelsberg** [comment]
> Built PR OK and testing features. So far very good.

Fixed build dependencies for latest dev commits.
Added automation trigger/condition "Pod Activated" (automated exports on patchpump types)

**Comment by vanelsberg** [comment]
Latest changes are mostly about improving Caraportal registration and the "Pod activated" automation trigger which enables automatic settings export on pod activation (EROS/DASH/Metrum/....).

(To dev's that would like to test...)
Think this could be the "final" PR for "field testing" finding possible bugs?

**Comment by MilosKozak** [comment]
could you merge dev to see real changes?

**Comment by MilosKozak** [comment]
Changed files 119 makes me worry little bit. Merge dev to this PR f it fix itself

**Comment by vanelsberg** [comment]
> Changed files 119 makes me worry little bit. Merge dev to this PR to see if it fix itself

@MilosKozak 
🙈My bad! Totally overlooked the PR had also dev changes...
To fix, I'll do a new PR

**Comment by vanelsberg** [comment]
@MilosKozak 
PR3487 **replaces this PR3463**

**Pull request closed without merging**
