### PR TITLE
Wear: tile support pump actions and temporary target

### PR DESCRIPTION
**Pull request by Andries-Smit**
Wear OS Tiles provide easy access to the information and actions users need in order to get things done.  Using the Tiles API requires targeting API level 26 or higher.

Tiles can be used to quickly access actions on the AAPS application, without going through the menu of the watch face.
The tiles are optional and can be added and configured with 1 to 4 actions by the user.  (Long press the tile, will show the configuration options)

Action tile can request the pump for: 
1. Calculation, based on carb input
1. Insulin 
1. Treatment: Insulin & Carbs 
1. Carbs
1. Temporary Target (target and time)
action_tile_preview

The Temp Target Tile can request a temporary target based on the phone app presents.
1. Activity
1. Hypo
1. Eating soon
1. Manual (target and time)
1. Cancel
image

Furthermore some small changes
1. Align action/menu naming with phone app (Bolus =>Treatment, eCarbs => Carbs, Wizard => Calculator)
1. Toast for shown after action request

**Compatibility note:**
- The watch-phone API is extended, making the change backward compatible. Watches that are still on 2.8.2.1 keep working
- Watch Minimum API is staying 23, Tested by @dlvoy on Sony SWR50
- Tiles can only be used watches with API level 26 or higher.

### CODE REVIEW

**Comment by erobinson** [comment]
Changes look great! Super excited! I'll see if I can find time to test them out.

**Comment by erobinson** [comment]
@Andries-Smit - Changes look great!! Thanks so much! The temp targets are super useful and will definitely use them a bunch! Tested it out and everything works as expected. 

The only thing that tripped me up at first (_SUPER SMALL_) was that for the temp target I tapped it multiple times before it came back w/ the confirmation. So then came back w/ multiple confirmations. Not sure if there's a simple animation you can add on the button click or something so the user knows to wait. But totally not a big deal once you've done it once you know to wait.

Thanks again for the work! The code changes look solid to me!

**Comment by vanelsberg** [comment]
@Andries-Smit Awesome!
Works quite good in general!
Encountered a bug when editing the "actions" tile however.
Trying to selecting "Wizard" for action exits edit action. Retrying a second time stops the watchface all together. To restore I need to restart the watch and if that does not solve, reinstall.

**Comment by vanelsberg** [comment]
Calculator default to 100%.
Would suggest 75% for default or using the percentage value set in preferences.

**Comment by vanelsberg** [comment]
TDD for EROS (and DASH?) errors out with "Cannot load from pump. No history data"

**Comment by vanelsberg** [comment]
Would be nice to have a tile option for showing status info (in particular for Pump and Loop).
Currently this is only available from the watchface rotary menu.

**Comment by Andries-Smit** [comment]
@erobinson 
> The only thing that tripped me up at first (_SUPER SMALL_) was that for the temp target I tapped it multiple times before it came back w/ the confirmation. So then came back w/ multiple confirmations. Not sure if there's a simple animation you can add on the button click or something so the user knows to wait. But totally not a big deal once you've done it once you know to wait.

There should be a Toast message `Temp Target Requested` Thereafter the confirmation will be received from the phone. I will take in the suggestion to show an animation and maybe even a TT state for the next iteration. Technically it does not hurt to have it executed multiple times.

**Comment by Andries-Smit** [comment]
@vanelsberg 
> Currently, for me the action tile only shows 3 actions. When trying to selecting action#1 (showing "Wizard", which is not on the tile) immediately exits edit mode.

I made a typo and corrected the setting key. This made action disappear from the tile as expected. When trying to open the preferences, the preference manager could not deal with the missing option. Uninstall, re-install removed the faulty preference value. 
https://github.com/Andries-Smit/AndroidAPS/commit/31cf560d3e9c480f4f28d0ac2a0f8d310d476af6#diff-38d7b2279ead83910e73ab898396560e289727941da7015e3a970ac46f2c0da3https://github.com/Andries-Smit/AndroidAPS/commit/31cf560d3e9c480f4f28d0ac2a0f8d310d476af6#diff-38d7b2279ead83910e73ab898396560e289727941da7015e3a970ac46f2c0da3

> Calculator defaults to 100%.
A good feature request, though it is not related to the tile PR. 

> "Cannot load from pump. No history data"
This issue is not related to this PR, as it is implemented in the phone app. We can have a look at it at a later stage

>  showing status info (pump and loop)
Feature request for the future. The AAPS home 2 watch face has the last update time.

**Comment by vanelsberg** [comment]
> Currently, for me the action tile only shows 3 actions. When trying to selecting action#1 (showing "Wizard", which is not on the tile) immediately exits edit mode.

Bug fixed!

**Comment by vanelsberg** [comment]
Looks good.
No issues found.

**Comment by vanelsberg** [comment]
All functions tested OK on Samsung Watch 4 Classic.

**Comment by Andries-Smit** [comment]
Dev & testing completed. @dlvoy tested on Sony SWR50

**Comment by vanelsberg** [comment]
Retested latest commits for Samsung Galaxy Watch 4 Classic.
All green. I think this is ready for merging with dev.

**Comment by markvader** [comment]
Tile support, tested on TicWatch Pro 3 GPS (Wear OS2).  All works as expected.

**Comment by vanelsberg** [comment]
Have been using this daily for over a week now, also with PR#1195
No issues.

**Comment by erobinson** [comment]
Tested this for a few weeks, working well.

**Comment by Andries-Smit** [comment]
Merged with https://github.com/nightscout/AndroidAPS/pull/1317

**Pull request closed without merging**
