### PR TITLE
bypasses the NSServer certificate check in engineering mode

### PR DESCRIPTION
**Pull request by lvlv**
We currently need a full functional NSServer for AAPS to connect even in debug/engineering mode.
This change bypasses the NSServer certificate check in engineering mode, making it easier for developers to build a local server.

### CODE REVIEW

**Comment by MilosKozak** [comment]
i don't think this should be in master. Do it for yourself

**Comment by lvlv** [comment]
> i don't think this should be in master. Do it for yourself

That will be a burden for those who build local ns server. I have to patch over every time I upgrades.
May I know your concern?

**Comment by lvlv** [comment]
We do see a lot of requests on discord:
image

If disabling cert checks in engineering mode is not a good choice, will a new option to "allow insecure https server" be better?

**Comment by swissalpine** [comment]
> I have to patch over every time I upgrade.

You can commit your changes to keep them! Multiple patches aren't necessary.

**Comment by lvlv** [comment]
> > I have to patch over every time I upgrade.
> 
> You can commit your changes to keep them! Multiple patches aren't necessary.

Sorry, I can't catch it, even if I committed my changes, we have to rebase on new versions every 90 days when we are forced to upgrade.

**Comment by swissalpine** [comment]
No, just pull the changes. I modified a lot of the code to my needs. That's no problem.

**Comment by lvlv** [comment]
> No, just pull the changes. I modified a lot of the code to my needs. That's no problem.

You are betting no conflicting changes. This is certainly not friendly to end users.

**Comment by swissalpine** [comment]
No, but normaly I'm capable to solve them.

**Comment by vanelsberg** [comment]
> i don't think this should be in master. Do it for yourself

Agree. As far as I can tell this disables SSL checking always when in developer mode? 
I do not think we should want that?

Running dev versions 90% personally I would not! For a developer there are other ways to get by, for instance with a self-signed cert or using a free certificate from Let's Encrypt.

**Comment by lvlv** [comment]
I think use an option to whitelist a specific cert should be a better
choice, but I didn't try that out.

Theodoor ***@***.***> 于 2022年11月19日周六 上午6:45写道：

**Comment by savek-cc** [comment]
Maybe even "just"(?) install the self signed NS-cert into the android certificate store (so independent of AAPS)?
https://coderwall.com/p/wv6fpq/add-self-signed-ssl-certificate-to-android-for-browsing

**Pull request closed without merging**
