### PR TITLE
small font for material button

### PR DESCRIPTION
**Pull request by osodebailar**
@swissalpine : Please test this on your mini phone

Issue: https://github.com/nightscout/AndroidAPS/issues/1648

### CODE REVIEW

**Comment by swissalpine** [comment]
Thank you for taking the point.
Unfortunately the font size does not change after merging your branch. The problem still exists.

**Comment by osodebailar** [comment]
I set the font size from 10 to 8sp and the padding to 0. maybe we can try „dp“ instead of „sp“

**Comment by swissalpine** [comment]
Yes, that is probably the reason. I actually changed to dp almost everywhere because my system-wide large font size destroys any layout otherwise.

**Comment by osodebailar** [comment]
> Yes, that is probably the reason. I actually changed to dp almost everywhere because my system-wide large font size destroys any layout otherwise.

@swissalpine  Lets try again . change to dp and make letter spacing smaller

**Comment by swissalpine** [comment]
Thank you for your continued work.
There are still two lines too many in dialog_loop.xml which should be deleted (300-301):
```
android:textAppearance="@style/TextAppearance.AppCompat.Medium"
android:textSize="11sp"
```
Beside it fits _for me_, if the following changes in the styles.xml are still added:
The font can be 12 dp (10dp is already too small ...), maybe <... padding-top>0dp</item> is another possibility to get the buttons a bit smaller. But it would be even better if the distance between icon and text would be smaller, at least that's how it was before. But I don't know how to do that ...
Here is my excerpt from the style.xml:
```
    <style name="ButtonSmallFontStyle" parent="GrayButton">
        <item name="android:letterSpacing">0</item>
        <item name="android:paddingTop">0dp</item>
        <item name="android:paddingStart">0dp</item>
        <item name="android:paddingEnd">0dp</item>
        <item name="android:textSize">12dp</item>
    </style>
```
What do you think?

**Comment by osodebailar** [comment]
> Thank you for your continued work. There are still two lines too many in dialog_loop.xml which should be deleted (300-301):
> 
> ```
> android:textAppearance="@style/TextAppearance.AppCompat.Medium"
> android:textSize="11sp"
> ```
> 
> Beside it fits _for me_, if the following changes in the styles.xml are still added: The font can be 12 dp (10dp is already too small ...), maybe <... padding-top>0dp is another possibility to get the buttons a bit smaller. But it would be even better if the distance between icon and text would be smaller, at least that's how it was before. But I don't know how to do that ... Here is my excerpt from the style.xml:
> 
> ```
>     <style name="ButtonSmallFontStyle" parent="GrayButton">
>         <item name="android:letterSpacing">0</item>
>         <item name="android:paddingTop">0dp</item>
>         <item name="android:paddingStart">0dp</item>
>         <item name="android:paddingEnd">0dp</item>
>         <item name="android:textSize">12dp</item>
>     </style>
> ```
> 
> What do you think?

Thanks. 
I removed the lines that i overlooked add top padding and set the fontsize to 11dp. For longer texts ( quickwizard button ) its better to act with 11 instead of 12.

@swissalpine : can you test please again  and say ok for merging ?

**Comment by swissalpine** [comment]
No, it all fits back on the pages, that's really o.k. I think - but reading the writing is difficult for an old man like me. But better this way than the other.
Quickwizzard I don't use, so 12 dp would have fit for me, but I think this word blows everything up.
Here are the current screenshots:
Screenshot_20220420-181224
Screenshot_20220420-181211
Thanks for finding a solution!

**Comment by osodebailar** [comment]
@swissalpine thanks for testing .
@MilosKozak we can merge the solution.

**Pull request merged**
