### PR TITLE
PR3296 auto export (DRAFT)

### PR DESCRIPTION
**Pull request by vanelsberg**
**This PR#3451 enables automated settings export.**
As settings export needs the master password for encryption the password is stored on the local phone's app datastore on manually exporting settings from the maintenance menu. Password will expire/wipe when not used for the number of days set.
Stored password wil be wiped on settings master password (or forced with file 'ExportPasswordReset' in /AAPS/extra)

Functionality is enabled through a new setting in Maintenance preferences.
Once enabled (and password set through manual export) user can define the automatic settings export from automation.

Actions also wil be in registered to "Treatments" (careportal/User entry)

_TODO_: Review/determine if storing the master password unencrypted local phone's app storage is acceptable.
See also issue https://github.com/nightscout/AndroidAPS/issues/3296

**Additional note**:
This PR implementation should enable implementation for auto exporting to alternate storage locations (like the Downloads folder or Cloud). But this will be subject for another PR.

### CODE REVIEW

**Comment by vanelsberg** [comment]
@Milos Needs some help on Quality checks please?
Tests: todo for final PR. 
Code duplication: can see the problem?
(FUI: Testen PR merge ok at my end)

**Comment by vanelsberg** [comment]
> where is the password stored?

On the phone's local storage (app's data store). Unencrypted but "protected" as one needs to connect through the debugger to get access). Stored password will be removed when not used as per expiry setting.

Even though not encrypted, question is what encryption would add?
Imho for getting the stored password is not relevant as retrieving the master password is easy (user:) through password reset or (devs:) debugger niffing?

Module has "hooks" for encryption/decryption (but that would need another password/key, filling in needs additional research)

**Comment by robertrub** [comment]
Testing this PR. All seems to be working as expected. No psw is asked for settings export (after Medtrum Nano activation) and the automation is exporting settings as planned.
Has set _forget password_ to 14 days. Waiting for that limit to arrive.

**Comment by vanelsberg** [comment]
Working on a new PR that is securely encrypting the password required for unattended exporting.
Expect details in the following weeks... ;-)

**Comment by olorinmaia** [comment]
Tested ok with an expiration of 7 days. I made an automation that automaticly exported settings when cannula age was less the 0,1 hours. It worked great! My biggest wish for this is not to be needed to re enter password and eventually add upload to google drive! Great work!

**Comment by vanelsberg** [comment]
> Tested ok
Great to here 👍 
New PR will have similar functionality with improved code and securely encrypted password.

> .. eventually add upload ...
Exporting to alternative locations like Cloud can be in a follow up PR which builds on this.

**Comment by robertrub** [comment]
I think, it is better to ask for the psw regularly. If not, the day when it will be needed, nobody will remember it... Most people do not use password apps.

ATM, the number of days is set by the user.

**Comment by olorinmaia** [comment]
I see your point. My android phone saves password in google account. I also keep a backup of it in another file just in case. It should surely be an option if you dont want to re enter if it is possible

**Comment by vanelsberg** [comment]
> Can password then be stored indefinetely?

Nope. Password expires after 4 weeks, with 1 week glare period.
User gets alert when this is the case.

> To import settings on another phone, if that what we are afraid of, it will be needed to re-enter password.
Nothing changes there. Stored password will only be available on the phone it was stored.

**Comment by vanelsberg** [comment]
Exactly that 👍 

> ATM, the number of days is set by the user.

In the new PR - no longer. Expiry will be fixed at 4 weeks.

**Comment by vanelsberg** [comment]
**Clasing the PR soon.**
Will be replaced by a new PR. See https://github.com/nightscout/AndroidAPS/issues/3461

**Comment by vanelsberg** [comment]
Closed the draft PR, will replace with new more final PR

**Pull request closed without merging**
