### PR TITLE
Add Equil Patch Pump

### PR DESCRIPTION
**Pull request by EquilHack**
This project primarily integrates a Bluetooth driver named Equil Patch Pump, enabling it to operate with AndroidAPS.  The driver is based on Equil Patch Pump firmware version 5.3.

### CODE REVIEW

**Comment by MilosKozak** [comment]
your PR must be dev branch based
can you contact me on some chat?

**Comment by EquilHack** [comment]
> your PR must be dev branch based can you contact me on some chat?

Of course, or we can just discuss here 

my email :equilhack@mailfence.com

**Comment by gerardocapp** [comment]
Good morning to the group. during the ATTD conference in Hamburg I received the Equil patch to use with aps. I ask if I can receive the code to test the pump with AAPS

**Comment by birdfly** [comment]
> Good morning to the group. during the ATTD conference in Hamburg I received the Equil patch to use with aps. I ask if I can receive the code to test the pump with AAPS

Do you know how and where we can get the pump？ the code can be found from @EquilHack's repository , but we need devices to test ,then the community would decide to merge or not

**Comment by gerardocapp** [comment]
> > Good morning to the group. during the ATTD conference in Hamburg I received the Equil patch to use with aps. I ask if I can receive the code to test the pump with AAPS
> 
> Do you know how and where we can get the pump？ the code can be found from @EquilHack's repository , but we need devices to test ,then the community would decide to merge or not

Hi, I can try asking directly to the administrator of the microtech I'm in contact with... I'll update you and

**Pull request closed without merging**
