### PR TITLE
open app on notification press

### PR DESCRIPTION
**Pull request by AdrianLxM**
This will allow to open the app on tap of (system) overview notifications.
https://github.com/nightscout/AndroidAPS/issues/101

Also: small cleanups - removing code duplication.
Also: make system notifications the default option.

### CODE REVIEW

**Comment by StephenBrown2** [comment]
Should this have been merged into dev?

**Comment by StephenBrown2** [comment]
@AdrianLxM this is great! It opens the app when I tap the notification. However, two things are missing. One that I didn't realize I was expecting, and the other that I'd hoped for in the original request:
- The notification is not dismissed on tap
- The app opens to the main activity, rather than the activity that relates to the notification (Pump Unreachable -> Medtronic tab)

I'm sure the latter is much more complex than the former, especially if the notification is coming from NS and not the app.

**Comment by AdrianLxM** [comment]
@StephenBrown2 it will open the app. So most likely you will be directly on the Overview where the in-app notification is shown that gets mirrored by the system notification. In the Overview you can mute the notification.

Navigating to a certain plugin is hard. It could be in different places in the app - or even another plugin might make much more sense. E.g. if no CGM values arrive the overview again.

So I went for the MVP here.

**Comment by StephenBrown2** [comment]
> Navigating to a certain plugin is hard. It could be in different places in the app - or even another plugin might make much more sense. E.g. if no CGM values arrive the overview again.
> 
> So I went for the MVP here.

That's what I figured. 👍🏻 

> In the Overview you can mute the notification.

But this won't dismiss the system notification (or at least, it hasn't in my recent testing)

**Comment by AdrianLxM** [comment]
> But this won't dismiss the system notification (or at least, it hasn't in my recent testing)

Would you mind trying to reproduce that and open another issue if it still happens. I fear in an already merged PR this will get lost.
I'll then take a look.

Thanks!

**Comment by StephenBrown2** [comment]
Sure thing, I'll watch for it and create a new issue when it happens.

**Pull request merged**
