### PR TITLE
Add a Checkbox to simplify main graph (hide TherapyEvents from graph)

### PR DESCRIPTION
**Pull request by Philoul**
What do you think of this proposal (see #905)
Only therapyEvents are hidden if checkbox unchecked... (I think it's important to keep all other events)
image

### CODE REVIEW

**Comment by vanelsberg** [comment]
Yes. Think this is a good idea. Would love to see that option in.
Could it maybe also hide the profile changes? There are times I want to see them, but most of the time for me they are cluttering the view.

**Comment by Philoul** [comment]
@vanelsberg hiding Profile Switch at the same time is easy to do, but I'm not convinced it's a good idea:
-> Profile Switches should be quite rare in every looper's time line (temporary PS for exercises or for special events and one-time PS for updating profile) and Selected Profile at any time is one of the most important information concerning user's loop (all main parameters are defined in your profile)
Can you explain to me why you have so many PS that your main graph becomes unreadable?
@MilosKozak , do you have any comments concerning this PR (with or without @vanelsberg's additional request)?

**Comment by vanelsberg** [comment]
@Philoul In case of the screen print I had been experimenting/adhusting my profile.
In general I do use Profile switches:

- For special meal (e.g: pizza) - setting a 2 hour 130% and AAPS/SMB handles that perfectly.
- My insulin sensitivity changes a lot and unpredictably by day and even by day time (morning/midday/evening/night). So much that even oRef's autosense feature can not keep up. So when I have my "off-day" I use a switch profile to 120% for hours to keep on target. 

I know when I intentionally do a profile switch. So I have no need to see them in the overview all the time unless I am looking for an event or improvement. And then profile switches and other info are be far better viewable under treatments.

**Comment by rustymonkey** [comment]
The Overview screen/graph is already quite 'busy'. This functionality is useful, though, so would it be feasible for it to instead appear as an option within the graph menu to keep the graph clean? e.g.
[x] Predictions
[x] Basals
[ ] Activity
[ ] Events <--------

**Comment by MilosKozak** [comment]
replaced by https://github.com/nightscout/AndroidAPS/commit/8fee28bcb7226aaae8b467391747bdd3e0ee9796

**Pull request closed without merging**
