### PR TITLE
Fixes timezone-dependent failing DateUtilTest

### PR DESCRIPTION
**Pull request by ryanhaining**
Issue #2745, #2747

### CODE REVIEW

**Comment by MilosKozak** [comment]
thanks
this should go directly to `TestBase` as it can happen anywhere
why assertThat?

**Comment by ryanhaining** [comment]
>  this should go directly to TestBase as it can happen anywhere

I recommend against adding that setup logic to every test since it isn't relevant for most tests. The `DateUtilTest` is the only one that's failing for me without it.

>  why assertThat? Assertions.assertTrue is junit5 thus not depending on another lib

I show the test output  in #2745 with `assertTrue` (the failure I was originally getting) and `assertThat`. Using specific matchers like this is common, [the project already depends on truth](https://github.com/nightscout/AndroidAPS/blob/dev/core/main/test_dependencies.gradle#L9). I wasn't able to understand the problem with `assertTrue`

Related, I am interested in contributing more to this project, and would like to start with improving tests and test coverage  since I do so much of it in my real job.

**Comment by ryanhaining** [comment]
My email address is in my profile, contact me if you'd like to discuss any of that more directly, I have the usual apps.

**Comment by MilosKozak** [comment]
@ryanhaining awesome if you can contribute on tests. I'm working on it wery slowly. Please PM me on discord

**Comment by ryanhaining** [comment]
Sent FR

**Pull request merged**
